import { useEffect, useState } from "react";
import { Button, Field, PageHeader, StatusPill, Surface } from "@webui/sdk/ui";
import { useWebUITranslation } from "@webui/sdk/i18n";
import { createDepartment, departmentTree, updateDepartment, type DepartmentNode } from "./api";
import styles from "./organization.module.css";

function flatten(nodes:DepartmentNode[],depth=0):Array<{item:DepartmentNode;depth:number}>{return nodes.flatMap((item)=>[{item,depth},...flatten(item.children,depth+1)]);}
export default function DepartmentsPage(){const {t}=useWebUITranslation("webui.organization");const [items,setItems]=useState<DepartmentNode[]>([]);const [code,setCode]=useState("");const [name,setName]=useState("");const [parentId,setParentId]=useState("");const refresh=()=>departmentTree().then(setItems);useEffect(()=>{void refresh();},[]);const flat=flatten(items);return <div className={`${styles.organizationModule} module-page`}><PageHeader eyebrow={t("webui.organization.brand")} title={t("webui.organization.departments.title")} description={t("webui.organization.departments.description")}/><Surface className="toolbar"><Field label={t("webui.organization.code")} value={code} onChange={(event)=>setCode(event.target.value)}/><Field label={t("webui.organization.name")} value={name} onChange={(event)=>setName(event.target.value)}/><label>{t("webui.organization.parent")}<select value={parentId} onChange={(event)=>setParentId(event.target.value)}><option value="">—</option>{flat.map(({item})=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button onClick={()=>void createDepartment(code,name,parentId).then(()=>{setCode("");setName("");return refresh();})}>{t("webui.organization.create")}</Button></Surface><div className="admin-grid">{flat.map(({item,depth})=><Surface className="admin-card" key={item.id}><div style={{paddingLeft:depth*18}}><h2>{item.name}</h2><p>{item.code}</p></div><div className="admin-meta"><StatusPill state={item.active&&!item.archived?"available":"unavailable"}>{item.archived?t("webui.organization.archived"):t("webui.organization.active")}</StatusPill><Button onClick={()=>void updateDepartment(item,{archived:!item.archived}).then(refresh)}>{item.archived?t("webui.organization.restore"):t("webui.organization.archive")}</Button></div></Surface>)}</div></div>}
export { flatten };
