package contract

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

type inventoryOperation struct {
	ID         string
	StrictName string
	Method     string
	Path       string
	Policy     string
	Scope      string
	Action     string
}

// GenerateOperationsGo 把模块契约渲染为 operation_inventory.gen.go 源码，语义与生成物一致。
func GenerateOperationsGo(packageName string, modules []Module) ([]byte, error) {
	operations, err := flattenOperations(modules)
	if err != nil {
		return nil, err
	}
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by contract-gen; DO NOT EDIT.\n\npackage %s\n\n", packageName)
	source.WriteString("// OperationID 是公开契约中的稳定 operationId。\ntype OperationID string\n\n")
	source.WriteString("// Operation 描述公开路由的低基数身份与策略。\ntype Operation struct {\n\tID OperationID\n\tMethod string\n\tPath string\n\tPolicy string\n\tScope string\n\tAction string\n}\n\n")
	source.WriteString("const (\n")
	for _, item := range operations {
		fmt.Fprintf(&source, "\tOperation%s OperationID = %s\n", goOperationName(item.ID), strconvQuote(item.ID))
	}
	source.WriteString(")\n\nvar operationInventory = [...]Operation{\n")
	for _, item := range operations {
		fmt.Fprintf(&source, "\t{ID: Operation%s, Method: %s, Path: %s, Policy: %s, Scope: %s, Action: %s},\n",
			goOperationName(item.ID), strconvQuote(item.Method), strconvQuote(item.Path),
			strconvQuote(item.Policy), strconvQuote(item.Scope), strconvQuote(item.Action))
	}
	source.WriteString("}\n\n")
	source.WriteString("// Operations 返回 inventory 副本。\nfunc Operations() []Operation {\n\treturn append([]Operation(nil), operationInventory[:]...)\n}\n\n")
	source.WriteString("// OperationForStrictName 把 strict middleware 名称映射回原始 operationId。\nfunc OperationForStrictName(name string) (Operation, bool) {\n\tswitch name {\n")
	for _, item := range operations {
		fmt.Fprintf(&source, "\tcase %s:\n\t\treturn Operation{ID: Operation%s, Method: %s, Path: %s, Policy: %s, Scope: %s, Action: %s}, true\n",
			strconvQuote(item.StrictName), goOperationName(item.ID), strconvQuote(item.Method), strconvQuote(item.Path),
			strconvQuote(item.Policy), strconvQuote(item.Scope), strconvQuote(item.Action))
	}
	source.WriteString("\tdefault:\n\t\treturn Operation{}, false\n\t}\n}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format operation inventory: %w", err)
	}
	return formatted, nil
}

func flattenOperations(modules []Module) ([]inventoryOperation, error) {
	if err := validateModules(modules); err != nil {
		return nil, err
	}
	result := make([]inventoryOperation, 0)
	strictNames := make(map[string]string)
	for _, module := range modules {
		for _, op := range module.Operations {
			strictName := goOperationName(string(op.ID))
			if owner, exists := strictNames[strictName]; exists {
				return nil, fmt.Errorf("operationIds %q and %q map to the same Go identity %q", owner, op.ID, strictName)
			}
			strictNames[strictName] = string(op.ID)
			result = append(result, inventoryOperation{
				ID: string(op.ID), StrictName: strictName,
				Method: string(op.Method), Path: op.Path,
				Policy: string(op.Policy.Mode), Scope: op.Policy.Scope, Action: op.Policy.Action,
			})
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result, nil
}

func goOperationName(value string) string {
	var result strings.Builder
	upperNext := true
	for _, character := range value {
		if character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z' || character >= '0' && character <= '9' {
			if upperNext && character >= 'a' && character <= 'z' {
				character -= 'a' - 'A'
			}
			result.WriteRune(character)
			upperNext = false
			continue
		}
		upperNext = true
	}
	return result.String()
}

func strconvQuote(value string) string { return fmt.Sprintf("%q", value) }
