/**
 * authority-codegen —— 确定性 Governance Composition Codegen。
 *
 * 职责：发现正式 Authority 的 Governance Contribution，确定性汇聚为
 * Resolved Governance Model 并生成 `apps/web/src/governance/generated-model.ts`
 * （Generated Artifact，带固定 GENERATED_HEADER）。
 *
 * Discovery 契约（与 plugin-codegen "文件即正式注册"同思路，无长期手工中央
 * Registry）：
 * - 遍历 pnpm workspace 内 `packages/*` 的 package.json；
 * - 其 exports 含 `./governance` 且指向真实文件 → 该 package 是正式 Authority；
 * - 用 Node type-stripping 加载其 governance 模块（governance.ts 只含 type-only
 *   import，无 CSS/React/vendor 运行时副作用）；
 * - 导出名约定 `governanceContribution`（Authority-owned Schema 的统一出口）。
 *
 * 校验：加载后经 `@community-go/schemas` 的 composeGovernance 纯规则校验
 * （identity/namespace/冲突/capability×mutability），失败 deterministic fail；
 * 生成产物带 fixed header，`--check` 逐字节比较 freshness（missing/drift/手改）。
 *
 * 本工具不 import 任何 Authority 的私有实现路径，也不解析目录结构推断事实；
 * 只消费显式 `./governance` 出口。
 */

import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const frontendRoot = resolve(import.meta.dirname, '..', '..');
const packagesRoot = join(frontendRoot, 'packages');
const outputPath = join(frontendRoot, 'apps', 'web', 'src', 'governance', 'generated-model.ts');

/** Generator ownership header（emission 与 freshness 共用单一来源）。 */
export const GENERATED_HEADER =
  '// @generated by tooling/authority-codegen —— 不要手改，运行 `pnpm codegen:governance` 重新生成。';

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function loadModule(path) {
  return import(pathToFileURL(path).href);
}

/**
 * Discovery：遍历 packages/* 找 exports 含 ./governance 的正式 Authority。
 * 排除 @community-go/schemas 自身（它是 Schema Contract Foundation，提供统一
 * Contract 与 ./governance 子路径，不是拥有治理事实的 Authority）。
 * 返回 [{ packageName, workspacePath, governanceExportPath, modulePath }]。
 */
export async function discoverGovernanceAuthorities() {
  const authorities = [];
  const entries = await readdir(packagesRoot, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const manifestPath = join(packagesRoot, entry.name, 'package.json');
    if (!(await exists(manifestPath))) continue;
    const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
    if (manifest.name === '@community-go/schemas') continue;
    const governanceTarget = manifest.exports?.['./governance'];
    if (!governanceTarget) continue;
    const modulePath = resolve(join(packagesRoot, entry.name), governanceTarget);
    if (!modulePath.startsWith(resolve(packagesRoot))) {
      throw new Error(`${entry.name}: ./governance 必须指向 packages/ 内文件`);
    }
    if (!(await exists(modulePath))) {
      throw new Error(`${entry.name}: ./governance 指向不存在的文件 ${modulePath}`);
    }
    authorities.push({
      packageName: manifest.name,
      workspacePath: `packages/${entry.name}`,
      governanceExportPath: `./governance`,
      modulePath,
    });
  }
  return [...authorities].sort((a, b) => a.packageName.localeCompare(b.packageName));
}

/** 渲染 generated-model.ts（generated header + prettier）。 */
async function renderGeneratedModel(authorities) {
  const lines = [];
  lines.push(GENERATED_HEADER);
  lines.push('');
  lines.push("import { composeGovernance } from '@community-go/schemas/governance';");
  lines.push("import type { ResolvedGovernanceModel } from '@community-go/schemas/governance';");
  lines.push('');
  for (const authority of authorities) {
    const alias = `contribution_${authority.packageName.replace(/[^A-Za-z0-9_]/g, '_')}`;
    lines.push(
      `import { governanceContribution as ${alias} } from ${JSON.stringify(`${authority.packageName}/governance`)};`,
    );
  }
  lines.push('');
  lines.push('// Resolved Governance Model：当前 Frontend Architecture 的机器可读治理投影。');
  lines.push('// 每个 Authority 在自己 Ownership 内维护 Governance Schema；本文件由');
  lines.push('// tooling/authority-codegen 确定性汇聚，不是手工维护的中央 Registry。');
  lines.push('export const resolvedGovernanceModel: ResolvedGovernanceModel = composeGovernance([');
  for (const authority of authorities) {
    const alias = `contribution_${authority.packageName.replace(/[^A-Za-z0-9_]/g, '_')}`;
    lines.push(`  ${alias},`);
  }
  lines.push(']);');
  lines.push('');
  return lines.join('\n');
}

async function formatCode(path, content) {
  const config = await prettier.resolveConfig(path);
  return prettier.format(content, { ...config, parser: 'typescript' });
}

async function renderFinalContent(content) {
  return formatCode(outputPath, content);
}

/* ------------------------------------------------------------------ */
/* Main                                                                */
/* ------------------------------------------------------------------ */

async function run(check) {
  const authorities = await discoverGovernanceAuthorities();

  // 加载全部 contribution 并做存在性/导出形状预检（确定性 fail）。
  // 完整规则校验（identity/namespace/冲突/capability×mutability）由
  // composeGovernance 在 apps/web 的 generated-model.ts 模块顶层执行
  // （web typecheck/test/build import 时 deterministic 暴露）——
  // 规则单一实现保持在 packages/schemas，authority-codegen 不复制规则。
  for (const authority of authorities) {
    const module = await loadModule(authority.modulePath);
    const contribution = module?.governanceContribution;
    if (!contribution || typeof contribution !== 'object') {
      throw new Error(
        `${authority.packageName}/governance 必须导出 governanceContribution（Authority-owned Schema 统一出口）`,
      );
    }
    if (!Array.isArray(contribution.domains) || contribution.domains.length === 0) {
      throw new Error(`${authority.packageName}/governance 必须声明至少一个 governance domain`);
    }
  }

  const content = await renderGeneratedModel(authorities);
  const expected = await renderFinalContent(content);

  if (check) {
    const drift = [];
    if (!existsSync(outputPath)) {
      drift.push(`missing: apps/web/src/governance/generated-model.ts`);
    } else {
      const actual = await readFile(outputPath, 'utf8');
      if (actual !== expected) {
        drift.push(
          `drift: apps/web/src/governance/generated-model.ts（运行 pnpm codegen:governance）`,
        );
      }
    }
    if (drift.length > 0) {
      console.error(
        `Authority governance codegen freshness failed:\n${drift.map((d) => `- ${d}`).join('\n')}`,
      );
      process.exitCode = 1;
      return;
    }
    console.log(`Authority governance codegen is fresh (${authorities.length} authorities).`);
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, expected);
  console.log(
    `Authority governance codegen generated: ${authorities.length} authorities → ${relative(frontendRoot, outputPath).split(sep).join('/')}`,
  );
}

const check = process.argv.includes('--check');
await run(check);
