/**
 * token-codegen —— Design System Token Generator（确定性生成 tokens.css）。
 *
 * 输入：packages/design-system/src/token-source/（纯 TS 数据，唯一 Source of Truth）。
 * 输出：packages/design-system/src/tokens.css（Generated Artifact，整文件重写）。
 *
 * 职责边界：
 * - 只从 token-source 渲染；不反向解析既有 tokens.css（禁止双向维护）；
 * - deterministic emission：先渲染 expected content，再写入；`--check` 模式
 *   逐字节比较（missing / drift / 手改 generated 文件 / stale 概念不适用——
 *   输出固定单文件）；
 * - tokens.css 首行必须等于 GENERATED_HEADER，否则 architecture gate 报
 *   "generated artifact 被人工修改"（boundary-policy 的"唯一硬编码颜色权威"
 *   路径不变，语义保持）。
 *
 * 说明：motion.css 是 Implementation-backed CSS 事实（keyframes/recipe 规则），
 * 不在本 generator 范围（保持人工维护，boundary-policy @keyframes 权威不变）。
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const frontendRoot = resolve(import.meta.dirname, '..', '..');
const tokenSourceRoot = join(frontendRoot, 'packages', 'design-system', 'src', 'token-source');
const tokensCssPath = join(frontendRoot, 'packages', 'design-system', 'src', 'tokens.css');

/** Generator ownership header（单一来源：emission 与 check 共用）。 */
export const GENERATED_HEADER =
  '/* @generated by tooling/token-codegen —— 不要手改，运行 `pnpm codegen:tokens` 重新生成。 */';

/* ------------------------------------------------------------------ */
/* Load token source（Node type-stripping；token-source 无副作用）        */
/* ------------------------------------------------------------------ */

async function loadModule(relativePath) {
  const module = await import(pathToFileURL(join(tokenSourceRoot, relativePath)).href);
  return module;
}

/* ------------------------------------------------------------------ */
/* 渲染 tokens.css（段顺序与人工版本一致：@theme → :root → dark → policy）  */
/* ------------------------------------------------------------------ */

/**
 * 渲染完整 tokens.css 文本。
 * @param semanticColors  { light, dark } 角色 → 值
 * @param colorOrder      语义色角色顺序（@theme 声明顺序）
 */
export function renderTokensCss({ semanticColors, colorOrder, themeScale, motion }) {
  const lines = [];
  lines.push(GENERATED_HEADER);
  lines.push('');

  // ---- @theme：语义映射与数值 ----
  lines.push('@theme {');
  lines.push(`  --font-sans: ${themeScale.fontSans};`);
  for (const role of colorOrder) {
    lines.push(`  --color-${role}: var(--ds-${role});`);
  }
  for (const [name, value] of Object.entries(themeScale.radii)) {
    lines.push(`  --radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(themeScale.spacings)) {
    lines.push(`  --spacing-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(themeScale.shadows)) {
    lines.push(`  --shadow-${name}: ${value};`);
  }
  lines.push(`  --ease-product: ${themeScale.easeProduct};`);
  // default transition-duration：未显式 duration 的 transition-* 统一归 control 语义
  lines.push('  --default-transition-duration: var(');
  lines.push('    --motion-duration-control');
  lines.push('  );');
  for (const [name, value] of Object.entries(themeScale.transitionDurations)) {
    lines.push(`  --transition-duration-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(themeScale.zIndices)) {
    lines.push(`  --z-index-${name}: ${value};`);
  }
  lines.push('}');
  lines.push('');

  // ---- :root（light 语义值 + motion 档位）----
  lines.push(':root {');
  lines.push('  color-scheme: light;');
  lines.push('  /* Motion Inspector 只调整调试倍率，基础档位仍是唯一数值权威。 */');
  lines.push('  --motion-debug-scale: 1;');
  lines.push('  /* Route content.enter 的前置 delay：方向进入无旧内容快照等待（纯 CSS 驱动），');
  lines.push('     与 content 档一致，保证页面切换响应快；方向感由位移本身表达。 */');
  lines.push(`  --motion-delay-route-forward: ${motion.delayRoute.forward};`);
  lines.push(`  --motion-delay-route-content: ${motion.delayRoute.content};`);
  for (const [name, value] of Object.entries(motion.durationBase)) {
    lines.push(`  --motion-duration-${name}: calc(${value} * var(--motion-debug-scale));`);
  }
  lines.push(
    '  /* 用途语义：动效按交互用途引用，不按数值引用（权威：docs/motion-foundation.md） */',
  );
  lines.push('  --motion-duration-control: var(');
  lines.push('    --motion-duration-fast');
  lines.push('  ); /* 组件自身状态动效（hover/press/switch 等） */');
  lines.push('  --motion-duration-feedback: var(');
  lines.push('    --motion-duration-standard');
  lines.push('  ); /* 反馈/异步状态动效（登记消费者：未来 FeedbackTransition） */');
  lines.push('  --motion-duration-page: var(');
  lines.push('    --motion-duration-slow');
  lines.push('  ); /* 页面级转场（消费者：motion.css 与未来页面容器） */');
  lines.push(
    '  /* 顶部进度条：进入/推进/补满/退出使用 progress 语义档位（消费者：top-progress 组件）。',
  );
  lines.push('   * --motion-duration-progress 是 Enter/Complete/Exit 的短档位（反馈语义）；');
  lines.push('   * --motion-duration-progress-cycle 是"从左侧持续延伸"的完整循环周期：');
  lines.push('   * 太短会让延伸肉眼不可辨，太长则等待感过重；1.1s 是克制的反馈节奏。');
  lines.push('   * 每次导航都保证一次完整视觉周期，不采用"导航太快就不显示"的门限策略。 */');
  lines.push(`  --motion-duration-progress: ${motion.durationProgress.progress};`);
  lines.push(`  --motion-duration-progress-cycle: ${motion.durationProgress['progress-cycle']};`);
  lines.push(
    `  --motion-distance-reveal: ${motion.distances.reveal}; /* 内容/区域进场抬升位移（content.enter 配方消费；登记：未来 section.reveal） */`,
  );
  lines.push(
    `  --motion-distance-enter: ${motion.distances.enter}; /* 页面内容方向进入位移（forward 方向 recipe 消费：右入克制位移，非手机重横滑） */`,
  );
  // light semantic color 值
  for (const role of colorOrder) {
    lines.push(`  --ds-${role}: ${semanticColors.light[role]};`);
  }
  lines.push('}');
  lines.push('');

  // ---- dark ----
  lines.push("[data-theme='dark'] {");
  lines.push('  color-scheme: dark;');
  for (const role of colorOrder) {
    lines.push(`  --ds-${role}: ${semanticColors.dark[role]};`);
  }
  lines.push('}');
  lines.push('');

  // ---- reduced-motion policy ----
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push("  html:not([data-motion-mode='full']) *,");
  lines.push("  html:not([data-motion-mode='full']) *::before,");
  lines.push("  html:not([data-motion-mode='full']) *::after {");
  lines.push('    scroll-behavior: auto;');
  lines.push('    animation-duration: 0.01ms;');
  lines.push('    animation-iteration-count: 1;');
  lines.push('    transition-duration: 0.01ms;');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push("html:is([data-motion-mode='reduced'], [data-motion-mode='off']) *,");
  lines.push("html:is([data-motion-mode='reduced'], [data-motion-mode='off']) *::before,");
  lines.push("html:is([data-motion-mode='reduced'], [data-motion-mode='off']) *::after {");
  lines.push('  scroll-behavior: auto;');
  lines.push('  animation-duration: 0.01ms;');
  lines.push('  animation-iteration-count: 1;');
  lines.push('  transition-duration: 0.01ms;');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** Prettier 格式化（与 repo 配置一致；CSS 用 css parser）。 */
async function formatCss(content) {
  const config = await prettier.resolveConfig(tokensCssPath);
  return prettier.format(content, { ...config, parser: 'css' });
}

/** 渲染最终内容：header + prettier。 */
export async function renderFinalTokensCss(sources) {
  const content = renderTokensCss(sources);
  return formatCss(content);
}

/* ------------------------------------------------------------------ */
/* Load + assemble sources                                             */
/* ------------------------------------------------------------------ */

export async function loadTokenSources() {
  const [semanticModule, scaleModule, motionModule, schemaModule] = await Promise.all([
    loadModule('semantic-colors.ts'),
    loadModule('theme-scale.ts'),
    loadModule('motion.ts'),
    loadModule('token-source.schema.ts'),
  ]);
  const semanticColors = semanticModule.getSemanticColorThemeTokens();
  const themeScale = scaleModule.getThemeScaleTokens();
  const motion = motionModule.getMotionTokenSource();

  // schema 校验（确定性 fail，绝不静默）
  const semanticParsed = schemaModule.semanticColorTokenSourceSchema.safeParse(semanticColors);
  if (!semanticParsed.success) {
    throw new Error(
      `Token Source 校验失败（semantic colors）: ${JSON.stringify(semanticParsed.error.issues)}`,
    );
  }
  const scaleParsed = schemaModule.themeScaleTokenSourceSchema.safeParse(themeScale);
  if (!scaleParsed.success) {
    throw new Error(
      `Token Source 校验失败（theme scale）: ${JSON.stringify(scaleParsed.error.issues)}`,
    );
  }
  const motionParsed = schemaModule.motionTokenSourceSchema.safeParse(motion);
  if (!motionParsed.success) {
    throw new Error(
      `Token Source 校验失败（motion）: ${JSON.stringify(motionParsed.error.issues)}`,
    );
  }

  // 语义色角色顺序（与既有人工 tokens.css 完全一致，保证生成零漂移）
  const colorOrder = Object.keys(semanticColors.light);
  return { semanticColors, colorOrder, themeScale, motion };
}

/* ------------------------------------------------------------------ */
/* CLI                                                                 */
/* ------------------------------------------------------------------ */

async function main() {
  const check = process.argv.includes('--check');
  const sources = await loadTokenSources();
  const expected = await renderFinalTokensCss(sources);

  if (check) {
    if (!existsSync(tokensCssPath)) {
      console.error('tokens.css missing: 请运行 `pnpm codegen:tokens` 生成。');
      process.exitCode = 1;
      return;
    }
    const actual = await readFile(tokensCssPath, 'utf8');
    if (actual !== expected) {
      console.error(
        'tokens.css drift: 运行 `pnpm codegen:tokens` 重新生成（Generated Artifact 禁止手改）。',
      );
      process.exitCode = 1;
      return;
    }
    console.log('Design token codegen is fresh.');
    return;
  }

  await mkdir(dirname(tokensCssPath), { recursive: true });
  await writeFile(tokensCssPath, expected);
  console.log('Design token codegen generated tokens.css from token-source.');
}

await main();
