// Command contract-gen 从 Huma registrations 生成 OpenAPI 与 operation inventory。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	iamhttp "github.com/rin721/go-scaffold-template/internal/module/iam/binding/http"
	navigationhttp "github.com/rin721/go-scaffold-template/internal/module/navigation/binding/http"
	organizationhttp "github.com/rin721/go-scaffold-template/internal/module/organization/binding/http"
	todohttp "github.com/rin721/go-scaffold-template/internal/module/todo/binding/http"
	"github.com/rin721/go-scaffold-template/internal/projectlayout"
	httptransport "github.com/rin721/go-scaffold-template/internal/transport/http"
	"github.com/rin721/go-scaffold-template/internal/transport/http/humabinding"
)

func main() {
	outputOpenAPI := flag.String("output-openapi", "", "生成的 OpenAPI 文件路径；留空时读取 project layout")
	outputInventory := flag.String("output-inventory", "", "生成的 operation inventory Go 文件路径；留空时读取 project layout")
	packageName := flag.String("package", "api", "生成 inventory 的 package")
	flag.Parse()
	if *outputOpenAPI == "" || *outputInventory == "" {
		root, layout, err := projectlayout.FindRepositoryRootFromCurrentDirectory()
		if err != nil {
			fail(err)
		}
		if *outputOpenAPI == "" {
			*outputOpenAPI, err = layout.RepositoryPath(root, layout.GeneratedArtifacts.OpenAPI)
			if err != nil {
				fail(err)
			}
		}
		if *outputInventory == "" {
			*outputInventory, err = layout.RepositoryPath(root, layout.GeneratedArtifacts.OperationInventory)
			if err != nil {
				fail(err)
			}
		}
	}
	if err := run(*outputOpenAPI, *outputInventory, *packageName); err != nil {
		fail(err)
	}
}
func fail(err error) { _, _ = fmt.Fprintln(os.Stderr, err); os.Exit(1) }

func run(outputOpenAPI, outputInventory, packageName string) error {
	registrations := registeredOperations()
	openAPI, err := httptransport.BuildHumaOpenAPI30(registrations...)
	if err != nil {
		return fmt.Errorf("build Huma OpenAPI: %w", err)
	}
	if err := writeFile(outputOpenAPI, openAPI); err != nil {
		return err
	}
	definitions, err := httptransport.BuildHumaOperationCatalog(registrations...)
	if err != nil {
		return err
	}
	inventory, err := generateInventory(packageName, definitions)
	if err != nil {
		return err
	}
	return writeFile(outputInventory, inventory)
}

func registeredOperations() []humabinding.Registration {
	return []humabinding.Registration{iamhttp.HumaRegistration(nil), organizationhttp.HumaRegistration(nil), navigationhttp.HumaRegistration(nil, nil), todohttp.HumaRegistration(nil)}
}

func generateInventory(packageName string, definitions []humabinding.Definition) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by contract-gen; DO NOT EDIT.\n\npackage %s\n\ntype OperationID string\n\ntype Operation struct { ID OperationID; Method, Path, Policy, Scope, Action string }\n\nconst (\n", packageName)
	for _, d := range definitions {
		fmt.Fprintf(&out, "\tOperation%s OperationID = %q\n", exportedName(d.ID), d.ID)
	}
	out.WriteString(")\n\nvar operationInventory = [...]Operation{\n")
	for _, d := range definitions {
		fmt.Fprintf(&out, "\t{ID: Operation%s, Method: %q, Path: %q, Policy: %q, Scope: %q, Action: %q},\n", exportedName(d.ID), d.Method, d.Path, d.Policy, d.Scope, d.Action)
	}
	out.WriteString("}\n\nfunc Operations() []Operation { return append([]Operation(nil), operationInventory[:]...) }\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format operation inventory: %w", err)
	}
	return formatted, nil
}
func exportedName(value string) string {
	fields := strings.FieldsFunc(value, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	for i, field := range fields {
		runes := []rune(field)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			fields[i] = string(runes)
		}
	}
	return strings.Join(fields, "")
}
func writeFile(path string, content []byte) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
