// @generated by tooling/authority-codegen —— 不要手改，运行 `pnpm codegen:governance` 重新生成。

import { composeGovernance } from '@community-go/schemas/governance';
import type { ResolvedGovernanceModel } from '@community-go/schemas/governance';

import { governanceContribution as contribution__community_go_design_system } from '@community-go/design-system/governance';
import { governanceContribution as contribution__community_go_plugin_framework } from '@community-go/plugin-framework/governance';
import { governanceContribution as contribution__community_go_state_foundation } from '@community-go/state-foundation/governance';
import { governanceContribution as contribution__community_go_surface_foundation } from '@community-go/surface-foundation/governance';
import { governanceContribution as contribution__community_go_ui_adapter } from '@community-go/ui-adapter/governance';

// Resolved Governance Model：当前 Frontend Architecture 的机器可读治理投影。
// 每个 Authority 在自己 Ownership 内维护 Governance Schema；本文件由
// tooling/authority-codegen 确定性汇聚，不是手工维护的中央 Registry。
export const resolvedGovernanceModel: ResolvedGovernanceModel = composeGovernance([
  contribution__community_go_design_system,
  contribution__community_go_plugin_framework,
  contribution__community_go_state_foundation,
  contribution__community_go_surface_foundation,
  contribution__community_go_ui_adapter,
]);
