import { InlineAlert, PageHeader, PageSection } from "@webui/sdk/ui";
import { useWebUITranslation } from "@webui/sdk/i18n";
import SwaggerUI from "swagger-ui-react";
import "swagger-ui-react/swagger-ui.css";
import { webuiOpenAPISpec, webuiOpenAPISpecSourceRevision } from "@webui/generated/openapi-spec";
import styles from "./openapi.module.css";

// OpenAPISpecView is the module-internal narrow wrapper around swagger-ui-react
// (R075-001): it owns the props and the third-party CSS entry point so the
// library never leaks into page assembly. The contract snapshot is generated by
// `webui generate` from api/openapi.yaml; the page issues no requests.
function OpenAPISpecView() {
  // The snapshot is a build-time JSON object. Hash deep-linking is disabled:
  // react-router owns the URL space, and the Swagger UI deep-link regression
  // (#10883) is therefore irrelevant here.
  return <div className={styles.specView}><SwaggerUI spec={webuiOpenAPISpec as object} docExpansion="none" tryItOutEnabled={false} deepLinking={false} /></div>;
}

export default function OpenAPIPage() {
  const { t } = useWebUITranslation("webui.openapi");
  const usable = typeof webuiOpenAPISpec === "object" && webuiOpenAPISpec !== null && !Array.isArray(webuiOpenAPISpec);
  const actions = usable ? undefined : <InlineAlert tone="danger" title={t("webui.openapi.docs.unavailable")} />;
  return <div className={`${styles.openapiModule} module-page`}>
    <PageHeader eyebrow={t("webui.openapi.docs.eyebrow")} title={t("webui.openapi.docs.title")} description={t("webui.openapi.docs.description")} />
    <div className="page-sections">
      <PageSection kicker={t("webui.openapi.docs.eyebrow")} title={t("webui.openapi.docs.legend.title")} description={t("webui.openapi.docs.legend.detail")} actions={actions}>
        {usable && <p className={styles.openapiSource}>{t("webui.openapi.docs.source", { revision: webuiOpenAPISpecSourceRevision })}</p>}
      </PageSection>
      {usable && <OpenAPISpecView />}
    </div>
  </div>;
}