import { Button, Field, FilePicker, SelectField, Spinner, Tabs, TextAreaField } from "@webui/sdk/ui";
import { useWebUITranslation } from "@webui/sdk/i18n";
import { MethodBadge } from "./MethodBadge";
import type { BodyType, FormFieldRow } from "./openapi-data";
import styles from "./openapi.module.css";

export type ParamEditorRow = { name: string; value: string; kind: "text" | "file"; required: boolean; description: string; location: "query" | "path" };
export type HeaderRow = { name: string; value: string };

export function RequestPane({ method, url, params, bodyTypes, bodyType, onBodyTypeChange, bodyText, onBodyTextChange, formRows, onFormChange, onFormFileChange, headers, cookies, executable, onParamChange, onAddParam, onRemoveParam, onHeaderChange, onAddHeader, onRemoveHeader, onCookieChange, onAddCookie, onRemoveCookie, bearer, onBearerChange, hasBearer, hasSession, onExecute, pending }: {
  method: string; url: string; params: ParamEditorRow[]; bodyTypes: BodyType[]; bodyType: BodyType; onBodyTypeChange: (type: BodyType) => void; bodyText: string; onBodyTextChange: (value: string) => void; formRows: FormFieldRow[]; onFormChange: (name: string, value: string) => void; onFormFileChange: (name: string, file: File | undefined) => void; headers: HeaderRow[]; cookies: HeaderRow[]; executable: boolean; onParamChange: (index: number, patch: Partial<ParamEditorRow>) => void; onAddParam: () => void; onRemoveParam: (index: number) => void; onHeaderChange: (index: number, patch: Partial<HeaderRow>) => void; onAddHeader: () => void; onRemoveHeader: (index: number) => void; onCookieChange: (index: number, patch: Partial<HeaderRow>) => void; onAddCookie: () => void; onRemoveCookie: (index: number) => void; bearer: string; onBearerChange: (value: string) => void; hasBearer: boolean; hasSession: boolean; onExecute: () => void; pending: boolean;
}) {
  const { t } = useWebUITranslation("webui.openapi");
  const tabs = [
    { id: "params", label: t("webui.openapi.request.params"), content: <DynamicRows label={t("webui.openapi.request.params")} addLabel={t("webui.openapi.request.add")} onAdd={onAddParam} count={params.length}>{params.map((row, index) => <div className={styles.editorRow} key={index}><Field label={t("webui.openapi.table.name")} value={row.name} onChange={(event) => onParamChange(index, { name: event.target.value })} disabled={!executable} className={styles.editorCellInput} /><Field label={t("webui.openapi.table.type")} value={row.kind === "file" ? "file" : "string"} disabled className={styles.editorCellInput} /><Field label={t("webui.openapi.table.required")} value={row.required ? t("webui.openapi.table.yes") : ""} disabled className={styles.editorCellInput} /><Field label={t("webui.openapi.table.description")} value={row.description} onChange={(event) => onParamChange(index, { description: event.target.value })} disabled={!executable} className={styles.editorCellInput} /><RemoveButton label={t("webui.openapi.request.remove")} onClick={() => onRemoveParam(index)} /></div>)}</DynamicRows> },
    { id: "body", label: t("webui.openapi.detail.body"), content: <><div className={styles.formSectionHead}><h3 className={styles.formSectionTitle}>{t("webui.openapi.detail.body")}</h3>{bodyTypes.length > 1 && <SelectField label={t("webui.openapi.debug.bodyType")} value={bodyType} onValueChange={(value) => onBodyTypeChange(value as BodyType)} options={bodyTypes.map((type) => ({ value: type, label: t(`webui.openapi.debug.body.${type}`) }))} className={styles.bodyTypeSelect} />}</div>{bodyType === "json" ? <TextAreaField label={t("webui.openapi.debug.body.json")} value={bodyText} onValueChange={onBodyTextChange} rows={10} className={styles.bodyEditor} disabled={!executable} /> : <div className={styles.editorRows}>{formRows.map((field) => <div className={styles.editorRow} key={field.name}><span className={styles.editorCell}><code className={styles.monoCell}>{field.name}</code><span className={styles.formHint}>{field.kind}</span></span>{field.kind === "file" ? <FilePicker label={field.name} className={styles.fileInput} disabled={!executable} onFilesChange={(files) => onFormFileChange(field.name, files?.[0])} /> : <Field label={field.name} value={field.value} onChange={(event) => onFormChange(field.name, event.target.value)} disabled={!executable} className={styles.editorCellInput} />}</div>)}</div>}</> },
    { id: "headers", label: t("webui.openapi.debug.headers"), content: <HeaderRows label={t("webui.openapi.debug.headers")} addLabel={t("webui.openapi.request.add")} rows={headers} onAdd={onAddHeader} onChange={onHeaderChange} onRemove={onRemoveHeader} executable={executable} /> },
    { id: "cookies", label: t("webui.openapi.debug.cookies"), content: <><p className={styles.formHint}>{t("webui.openapi.debug.cookiesHint")}</p><HeaderRows label={t("webui.openapi.debug.cookies")} addLabel={t("webui.openapi.request.add")} rows={cookies} onAdd={onAddCookie} onChange={onCookieChange} onRemove={onRemoveCookie} executable={executable} /></> },
    { id: "auth", label: t("webui.openapi.detail.auth"), content: <div className={styles.formSection}>{hasBearer && <Field label={t("webui.openapi.auth.bearer")} type="password" value={bearer} onChange={(event) => onBearerChange(event.target.value)} placeholder={t("webui.openapi.auth.bearerPlaceholder")} disabled={!executable} className={styles.authField} />}{hasSession && <p className={styles.formHint}>{t("webui.openapi.auth.session")}</p>}</div> },
  ];
  return <div className={styles.requestPane}><div className={styles.requestUrlRow}><div className={styles.requestUrlMethod}><MethodBadge method={method} /></div><Field label={t("webui.openapi.request.url")} value={url} readOnly className={styles.requestUrlInput} />{executable && <Button type="button" onClick={onExecute} disabled={pending} data-testid="openapi-send">{pending && <Spinner label={t("webui.openapi.run.running")} size="sm" />}{t(pending ? "webui.openapi.run.running" : "webui.openapi.run.execute")}</Button>}</div><div className={styles.requestTabs}><Tabs label={t("webui.openapi.request.tabs")} defaultSelectedKey="params" items={tabs} /></div></div>;
}

function HeaderRows({ label, addLabel, rows, onAdd, onChange, onRemove, executable }: { label: string; addLabel: string; rows: HeaderRow[]; onAdd: () => void; onChange: (index: number, patch: Partial<HeaderRow>) => void; onRemove: (index: number) => void; executable: boolean }) {
  const { t } = useWebUITranslation("webui.openapi");
  return <DynamicRows label={label} addLabel={addLabel} onAdd={onAdd} count={rows.length}>{rows.map((row, index) => <div className={styles.editorRow} key={index}><Field label={t("webui.openapi.debug.name")} value={row.name} onChange={(event) => onChange(index, { name: event.target.value })} disabled={!executable} className={styles.editorCellInput} /><Field label={t("webui.openapi.debug.value")} value={row.value} onChange={(event) => onChange(index, { value: event.target.value })} disabled={!executable} className={styles.editorCellInput} /><RemoveButton label={t("webui.openapi.request.remove")} onClick={() => onRemove(index)} /></div>)}</DynamicRows>;
}
function DynamicRows({ label, addLabel, onAdd, count, children }: { label: string; addLabel: string; onAdd: () => void; count: number; children: React.ReactNode }) { return <section className={styles.formSection}><div className={styles.formSectionHead}><h3 className={styles.formSectionTitle}>{label}</h3><Button type="button" variant="ghost" onClick={onAdd} disabled={count > 20}>{addLabel}</Button></div><div className={styles.editorRows}>{children}</div></section>; }
function RemoveButton({ label, onClick }: { label: string; onClick: () => void }) { return <Button type="button" variant="ghost" aria-label={label} onClick={onClick}>−</Button>; }
