// @generated by tooling/admin-codegen —— 不要手改，运行 `pnpm codegen:admin` 重新生成。

import AdminRouteBridge_reference_resources_edit from '@community-go/admin-surface/generated/routes/reference_resources_edit';

// 薄入口：await Next params Promise 后转发稳定 params，保持 Route Context 发布与 Host 边界。
export default async function AdminRouteEntry({
  params,
}: Readonly<{ params: Promise<Readonly<Record<string, string>>> }>) {
  const resolvedParams = await params;
  return <AdminRouteBridge_reference_resources_edit params={resolvedParams} />;
}
