/**
 * admin-codegen —— 确定性 Admin Surface Codegen 工具（Architecture Gate 执行点）。
 *
 * 职责边界：
 * - Discovery：扫描 surfaces/admin/plugins/ 下各 plugin 的 plugin.ts 与 routes 树
 *   （每个路由目录一对 page 文件与 route.meta 文件）。
 * - Contract Validation：静态校验 1:1 配对、禁止 Next exports、namespace、override、冲突。
 * - Framework Descriptors：只生成静态 descriptors / catalog / bridges / composition / i18n。
 * - Host Capability Analysis：Static Export Host 对 [param] 路由返回 UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE，
 *   不生成 Next 入口并令 gate 失败（硬失败，不降级、不 generateStaticParams）。
 * - Host Route Generation：为静态 Route 生成 apps/admin-web/src/app/<mount>/... 薄入口。
 *
 * Registry（canonical hierarchy / navigation inheritance / breadcrumb / command / permission）
 * 由 @community-go/admin-framework registry 在运行时完成，Generator 不复制该逻辑。
 *
 * 本工具不执行 React 代码；route.meta.ts 通过 Node 24 type-stripping 静态加载。
 * 生成物全部带 `// @generated` 头；freshness check 逐文件重建比较（missing / drift / stale）。
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const frontendRoot = resolve(import.meta.dirname, '..', '..');
const surfaceRoot = join(frontendRoot, 'surfaces', 'admin');
const pluginsRoot = join(surfaceRoot, 'plugins');
const generatedRoot = join(surfaceRoot, 'generated');
const hostAppRoot = join(frontendRoot, 'apps', 'admin-web', 'src', 'app');
const surfacePackageName = '@community-go/admin-surface';

export const GENERATED_HEADER =
  '// @generated by tooling/admin-codegen —— 不要手改，运行 `pnpm codegen:admin` 重新生成。';

/* ------------------------------------------------------------------ */
/* Small helpers                                                       */
/* ------------------------------------------------------------------ */

async function exists(path) {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function walk(directory) {
  if (!existsSync(directory)) return [];
  const files = [];
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(fullPath)));
    else files.push(fullPath);
  }
  return files;
}

function toPosix(path) {
  return path.split(sep).join('/');
}

async function loadTypeScriptModule(path) {
  return import(pathToFileURL(path).href);
}

function escapeIdentifier(name) {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

/** routeId → generated bridge 文件名（无扩展）。 */
function bridgeFileName(routeId) {
  return escapeIdentifier(routeId);
}

/* ------------------------------------------------------------------ */
/* Discovery                                                           */
/* ------------------------------------------------------------------ */

export async function discoverSurface() {
  const plugins = [];
  for (const entry of await readdir(pluginsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pluginDir = join(pluginsRoot, entry.name);
    const manifestPath = join(pluginDir, 'plugin.ts');
    if (!(await exists(manifestPath))) continue;
    const manifestModule = await loadTypeScriptModule(manifestPath);
    const definition = manifestModule?.pluginDefinition;
    if (!definition?.pluginId || !definition?.mount) {
      throw new Error(`plugins/${entry.name}/plugin.ts 缺少合法 pluginDefinition`);
    }
    if (definition.mount !== `/${entry.name}` && typeof definition.mount !== 'string') {
      // mount 必须是字符串并已由 plugin.ts satisfies 校验；此处只保证可解析。
    }
    const i18nPath = join(pluginDir, 'i18n.ts');
    plugins.push({
      definition,
      dir: pluginDir,
      hasI18n: await exists(i18nPath),
    });
  }
  return [...plugins].sort((a, b) => a.definition.pluginId.localeCompare(b.definition.pluginId));
}

/* ------------------------------------------------------------------ */
/* Validation                                                          */
/* ------------------------------------------------------------------ */

const forbiddenPageExports = [
  'generateStaticParams',
  'generateMetadata',
  'generateViewport',
  'revalidate',
  'dynamic',
  'runtime',
  'preferredRegion',
  'fetchCache',
  'maxDuration',
  'dynamicParams',
];

function forbiddenPageExportFound(content) {
  return forbiddenPageExports.filter((name) => {
    const pattern = new RegExp(
      `export\\s+(?:const|let|function)\\s+${name}\\b|export\\s*\\{\\s*${name}\\b`,
    );
    return pattern.test(content);
  });
}

/** 解析 Plugin Page 的具名组件导出；确定性：全文件必须恰好导出一个组件函数。 */
async function resolvePageComponent(pagePath) {
  const content = await readFile(pagePath, 'utf8');
  const exports = [];
  const namedFunction = /export\s+function\s+([A-Za-z_$][\w$]*)\s*\(/g;
  for (const match of content.matchAll(namedFunction)) exports.push(match[1]);
  // export default function Name 也视为组件
  const defaultFunction = /export\s+default\s+function\s+([A-Za-z_$][\w$]*)\s*\(/;
  const defaultMatch = defaultFunction.exec(content);
  if (defaultMatch) exports.push(defaultMatch[1]);
  if (exports.length !== 1) {
    throw new Error(
      `${pagePath}: Plugin Page 必须恰好导出一个具名组件函数（找到 ${exports.length} 个：${exports.join(', ') || '无'}）`,
    );
  }
  return exports[0];
}

async function scanRoutesTree(plugin) {
  const routesDir = join(plugin.dir, 'routes');
  if (!existsSync(routesDir)) return [];
  const files = await walk(routesDir);
  const pageByDir = new Map();
  const metaByDir = new Map();
  for (const file of files) {
    const local = toPosix(relative(routesDir, file));
    const isPage = /page\.tsx?$/.test(local);
    const isMeta = local.endsWith('route.meta.ts');
    if (!isPage && !isMeta) continue;
    const dir = local.includes('/') ? local.slice(0, local.lastIndexOf('/')) : '';
    if (isPage) pageByDir.set(dir, file);
    if (isMeta) metaByDir.set(dir, file);
  }

  for (const dir of metaByDir.keys()) {
    if (!pageByDir.has(dir)) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: route.meta.ts 缺少 1:1 的 page.tsx`,
      );
    }
  }
  for (const dir of pageByDir.keys()) {
    if (!metaByDir.has(dir)) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: page.tsx 缺少 1:1 的 route.meta.ts`,
      );
    }
  }

  const routes = [];
  for (const dir of [...pageByDir.keys()].sort()) {
    const pagePath = pageByDir.get(dir);
    const metaPath = metaByDir.get(dir);
    for (const segment of dir === '' ? [] : dir.split('/')) {
      if (
        segment.includes('...') ||
        segment.startsWith('(') ||
        segment.startsWith('@') ||
        /^\[\[.+]]$/.test(segment)
      ) {
        throw new Error(
          `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: 禁止 catch-all、parallel、route group（${segment}）`,
        );
      }
    }
    const pageContent = await readFile(pagePath, 'utf8');
    const forbidden = forbiddenPageExportFound(pageContent);
    if (forbidden.length > 0) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: 禁止 Next 专用导出 ${forbidden.join(', ')}`,
      );
    }
    const metaModule = await loadTypeScriptModule(metaPath);
    const routeMeta = metaModule?.routeMeta;
    if (!routeMeta || typeof routeMeta !== 'object') {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: route.meta.ts 必须导出 routeMeta`,
      );
    }
    const componentExport = await resolvePageComponent(pagePath);
    const descriptor = buildDescriptor(plugin, dir, routeMeta);
    validateRouteMetaContract(plugin, dir, descriptor, routeMeta);
    routes.push({ dir, pagePath, metaPath, descriptor, componentExport });
  }
  return [...routes].sort((a, b) => a.descriptor.routeId.localeCompare(b.descriptor.routeId));
}

function buildDescriptor(plugin, relativeDir, routeMeta) {
  const pluginId = plugin.definition.pluginId;
  const segments = relativeDir === '' ? [] : relativeDir.split('/');
  const routeId = relativeDir === '' ? pluginId : `${pluginId}.${relativeDir.split('/').join('.')}`;
  const pattern =
    segments.length === 0
      ? plugin.definition.mount
      : `${plugin.definition.mount}/${segments.join('/')}`;
  const paramNames = segments
    .filter((segment) => /^\[[A-Za-z0-9_]+]$/.test(segment))
    .map((segment) => segment.slice(1, -1));

  const navigation = routeMeta.navigation;
  return {
    routeId,
    pluginId,
    path: segments.join('/'),
    segments,
    pattern,
    paramNames,
    hasNavigation: Boolean(navigation),
    ...(navigation?.navigationId ? { navigationId: navigation.navigationId } : {}),
    ...(navigation?.labelKey ? { labelKey: navigation.labelKey } : {}),
    ...(navigation?.groupId ? { groupId: navigation.groupId } : {}),
    ...(routeMeta.titleKey ? { titleKey: routeMeta.titleKey } : {}),
    ...(routeMeta.canonicalParentOverride
      ? { canonicalParentOverride: routeMeta.canonicalParentOverride }
      : {}),
    ...(routeMeta.activeNavigationOverride
      ? { activeNavigationOverride: routeMeta.activeNavigationOverride }
      : {}),
    ...(routeMeta.permissions?.length ? { permissions: routeMeta.permissions } : {}),
  };
}

function validateRouteMetaContract(plugin, relativeDir, descriptor, routeMeta) {
  const errors = [];
  const pluginId = plugin.definition.pluginId;
  if (routeMeta.navigation) {
    if (typeof routeMeta.navigation.navigationId !== 'string') {
      errors.push('navigation.navigationId 必须提供');
    } else if (
      routeMeta.navigation.navigationId !== pluginId &&
      !routeMeta.navigation.navigationId.startsWith(`${pluginId}.`)
    ) {
      errors.push(`navigation.navigationId 必须为 ${pluginId}.* namespace`);
    }
    if (typeof routeMeta.navigation.labelKey !== 'string' || !routeMeta.navigation.labelKey) {
      errors.push('navigation.labelKey 必须提供');
    }
    if (typeof routeMeta.navigation.groupId !== 'string' || !routeMeta.navigation.groupId) {
      errors.push('navigation.groupId 必须提供');
    }
  }
  if (routeMeta.canonicalParentOverride) {
    const override = routeMeta.canonicalParentOverride;
    if (typeof override.routeId !== 'string' || override.routeId.split('.')[0] !== pluginId) {
      errors.push('canonicalParentOverride.routeId 必须引用同 Plugin Route');
    }
    if (typeof override.rationale !== 'string' || !override.rationale.trim()) {
      errors.push('canonicalParentOverride 必须提供 rationale');
    }
  }
  if (routeMeta.activeNavigationOverride) {
    const override = routeMeta.activeNavigationOverride;
    if (
      typeof override.navigationId !== 'string' ||
      override.navigationId.split('.')[0] !== pluginId
    ) {
      errors.push('activeNavigationOverride.navigationId 必须为同 Plugin namespace');
    }
    if (typeof override.rationale !== 'string' || !override.rationale.trim()) {
      errors.push('activeNavigationOverride 必须提供 rationale');
    }
  }
  if (errors.length > 0) {
    throw new Error(
      `plugins/${pluginId}/routes/${relativeDir || '.'}: metadata 契约失败\n${errors.map((item) => `- ${item}`).join('\n')}`,
    );
  }
}

function validateCatalogConflicts(allRoutes, plugins) {
  const routeIds = new Set();
  const patterns = new Set();
  const mounts = new Set();
  const errors = [];
  for (const route of allRoutes) {
    if (routeIds.has(route.descriptor.routeId)) {
      errors.push(`重复 routeId: ${route.descriptor.routeId}`);
    }
    routeIds.add(route.descriptor.routeId);
    if (patterns.has(route.descriptor.pattern)) {
      errors.push(`重复 pattern: ${route.descriptor.pattern}`);
    }
    patterns.add(route.descriptor.pattern);
  }
  for (const plugin of plugins) {
    if (mounts.has(plugin.definition.mount)) {
      errors.push(`mount 冲突: ${plugin.definition.mount}`);
    }
    mounts.add(plugin.definition.mount);
  }
  if (errors.length > 0) {
    throw new Error(`Catalog 冲突:\n${errors.map((item) => `- ${item}`).join('\n')}`);
  }
}

/* ------------------------------------------------------------------ */
/* Text builders（emission 与 freshness 共用同一文本生成，保证确定一致） */
/* ------------------------------------------------------------------ */

function buildCatalogText(plugins, allRoutes) {
  const lines = [
    "import type { AdminRouteCatalog } from '@community-go/admin-framework';",
    '',
    'export const generatedRouteCatalog: AdminRouteCatalog = {',
    '  plugins: [',
  ];
  for (const plugin of plugins) {
    lines.push(
      `    { pluginId: ${JSON.stringify(plugin.definition.pluginId)}, mount: ${JSON.stringify(plugin.definition.mount)} },`,
    );
  }
  lines.push('  ],');
  lines.push('  routes: [');
  for (const route of allRoutes) {
    lines.push('    {');
    for (const [key, value] of Object.entries(route.descriptor)) {
      if (value === undefined || value === null) continue;
      lines.push(`      ${key}: ${JSON.stringify(value)},`);
    }
    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('};');
  return `${lines.join('\n')}\n`;
}

function buildCompositionText(plugins) {
  const i18nPlugins = plugins.filter((plugin) => plugin.hasI18n);
  const lines = [
    "import { createAdminRegistry } from '@community-go/admin-framework';",
    "import type { AdminRegistryModel } from '@community-go/admin-framework';",
    "import type { TranslationResources } from '@community-go/i18n';",
    "import { generatedRouteCatalog } from '../catalog/catalog';",
    "import { mergeTranslationResources, type AdminSurfaceComposition } from '../../src/composition';",
    "import { surfaceShellI18nResources } from '../../src/i18n';",
    ...i18nPlugins.map(
      (plugin) =>
        `import { pluginI18nResources as pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)} } from '../../plugins/${plugin.definition.pluginId}/i18n';`,
    ),
    '',
    'export const generatedSurfaceRegistry: AdminRegistryModel =',
    '  createAdminRegistry(generatedRouteCatalog);',
    '',
    'export const generatedSurfaceI18nResources: TranslationResources = mergeTranslationResources(',
    '  surfaceShellI18nResources,',
    ...i18nPlugins.map(
      (plugin) => `  pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)},`,
    ),
    ');',
    '',
    'export const generatedAdminSurfaceComposition: AdminSurfaceComposition = {',
    '  registryModel: generatedSurfaceRegistry,',
    '  i18nResources: generatedSurfaceI18nResources,',
    '};',
    '',
  ];
  return lines.join('\n');
}

function buildBridgeText(route) {
  const pageSpecifier = toPosix(
    relative(join(generatedRoot, 'routes'), route.pagePath).replace(/\.tsx?$/, ''),
  );
  return [
    "'use client';",
    '',
    "import { AdminRouteContextProvider } from '@community-go/admin-framework/route-context';",
    `import { ${route.componentExport} } from ${JSON.stringify(pageSpecifier)};`,
    '',
    'export default function AdminRouteBridge({',
    '  params,',
    '}: Readonly<{ params: Readonly<Record<string, string>> }>) {',
    '  return (',
    '    <AdminRouteContextProvider',
    `      value={{ routeId: ${JSON.stringify(route.descriptor.routeId)}, params }}`,
    '    >',
    `      <${route.componentExport} />`,
    '    </AdminRouteContextProvider>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function bridgeImportSpecifier(route) {
  return `${surfacePackageName}/generated/routes/${bridgeFileName(route.descriptor.routeId)}`;
}

function buildHostEntryText(route) {
  return [
    `import ${route.bridgeExportName} from ${JSON.stringify(bridgeImportSpecifier(route))};`,
    '',
    '// 薄入口：await Next params Promise 后转发稳定 params，保持 Route Context 发布与 Host 边界。',
    'export default async function AdminRouteEntry({',
    '  params,',
    '}: Readonly<{ params: Promise<Readonly<Record<string, string>>> }>) {',
    '  const resolvedParams = await params;',
    `  return <${route.bridgeExportName} params={resolvedParams} />;`,
    '}',
    '',
  ].join('\n');
}

function hostEntryPath(route) {
  return join(hostAppRoot, route.descriptor.pattern.replace(/^\//, ''), 'page.tsx');
}

async function ensureDir(path) {
  await mkdir(dirname(path), { recursive: true });
}

/** Prettier 格式化生成的文本（与 repo 根配置一致），保证 deterministic emission 与 format:check 同时通过。 */
async function formatCode(path, content) {
  const config = await prettier.resolveConfig(path);
  const parser = /\.(?:ts|tsx)$/.test(path) ? 'typescript' : 'babel';
  return prettier.format(content, { ...config, parser });
}

async function writeGenerated(path, content) {
  await ensureDir(path);
  const formatted = await formatCode(path, `${GENERATED_HEADER}\n\n${content.replace(/^\n+/, '')}`);
  await writeFile(path, formatted);
}

/* ------------------------------------------------------------------ */
/* Emission                                                            */
/* ------------------------------------------------------------------ */

async function generateAll() {
  const plugins = await discoverSurface();
  const collected = [];
  for (const plugin of plugins) {
    collected.push({ plugin, routes: await scanRoutesTree(plugin) });
  }
  const allRoutes = collected.flatMap((item) => item.routes);
  validateCatalogConflicts(allRoutes, plugins);

  // 动态 Route：Static Export Host 不支持 → 硬失败 gate。
  const dynamic = allRoutes.filter((route) => route.descriptor.paramNames.length > 0);
  if (dynamic.length > 0) {
    throw new Error(
      `Host capability gate 失败 (UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE): Static Export Host 不支持动态 Plugin Route\n${dynamic
        .map((route) => `- ${route.descriptor.routeId} (${route.descriptor.pattern})`)
        .join('\n')}`,
    );
  }

  await rm(generatedRoot, { recursive: true, force: true });
  await writeGenerated(
    join(generatedRoot, 'catalog', 'catalog.ts'),
    buildCatalogText(plugins, allRoutes),
  );
  await writeGenerated(
    join(generatedRoot, 'composition', 'composition.ts'),
    buildCompositionText(plugins),
  );
  await writeGenerated(
    join(generatedRoot, 'composition', 'i18n.ts'),
    "export { generatedSurfaceI18nResources } from './composition';\n",
  );

  for (const route of allRoutes) {
    const bridgeName = bridgeFileName(route.descriptor.routeId);
    await writeGenerated(
      join(generatedRoot, 'routes', `${bridgeName}.tsx`),
      buildBridgeText(route),
    );
    // Host 薄入口（generated within apps/admin-web）
    route.bridgeExportName = `AdminRouteBridge_${bridgeName}`;
    await ensureDir(hostEntryPath(route));
    const hostEntryText = await formatCode(
      hostEntryPath(route),
      `${GENERATED_HEADER}\n\n${buildHostEntryText(route)}`,
    );
    await writeFile(hostEntryPath(route), hostEntryText);
  }

  return {
    plugins: plugins.map((plugin) => plugin.definition.pluginId),
    routes: allRoutes.map((route) => route.descriptor.routeId),
  };
}

/* ------------------------------------------------------------------ */
/* Freshness check                                                     */
/* ------------------------------------------------------------------ */

async function checkFreshness() {
  const plugins = await discoverSurface();
  const collected = [];
  for (const plugin of plugins) {
    collected.push({ plugin, routes: await scanRoutesTree(plugin) });
  }
  const allRoutes = collected.flatMap((item) => item.routes);
  validateCatalogConflicts(allRoutes, plugins);
  const dynamic = allRoutes.filter((route) => route.descriptor.paramNames.length > 0);
  if (dynamic.length > 0) {
    throw new Error(
      `Host capability gate 失败 (UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE): Static Export Host 不支持动态 Plugin Route\n${dynamic
        .map((route) => `- ${route.descriptor.routeId} (${route.descriptor.pattern})`)
        .join('\n')}`,
    );
  }
  for (const route of allRoutes) {
    route.bridgeExportName = `AdminRouteBridge_${bridgeFileName(route.descriptor.routeId)}`;
  }

  const drift = [];
  const expectedGenerated = new Map();

  const generatedFiles = [
    ['catalog/catalog.ts', buildCatalogText(plugins, allRoutes)],
    ['composition/composition.ts', buildCompositionText(plugins)],
    ['composition/i18n.ts', "export { generatedSurfaceI18nResources } from './composition';\n"],
    ...allRoutes.map((route) => [
      `routes/${bridgeFileName(route.descriptor.routeId)}.tsx`,
      buildBridgeText(route),
    ]),
  ];
  for (const [local, text] of generatedFiles) {
    expectedGenerated.set(local, text);
  }

  for (const [local, text] of expectedGenerated) {
    await compareGenerated(drift, join(generatedRoot, local), local, text);
  }
  // stale: generated 目录中存在但不再期望的文件
  for (const file of await walk(generatedRoot)) {
    const local = toPosix(relative(generatedRoot, file));
    if (!expectedGenerated.has(local)) {
      drift.push(`stale generated file: surfaces/admin/generated/${local}`);
    }
  }

  // Host 薄入口
  for (const route of allRoutes) {
    const entryPath = hostEntryPath(route);
    const local = toPosix(relative(frontendRoot, entryPath));
    await compareGenerated(drift, entryPath, local, buildHostEntryText(route));
  }
  for (const file of await walk(join(hostAppRoot, 'reference-resources'))) {
    const local = toPosix(relative(frontendRoot, file));
    if (
      local.endsWith('page.tsx') &&
      ![...allRoutes].some((route) => hostEntryPath(route) === file)
    ) {
      drift.push(`stale host entry: ${local}`);
    }
  }

  return drift;
}

async function compareGenerated(drift, path, local, text) {
  const expected = await formatCode(path, `${GENERATED_HEADER}\n\n${text.replace(/^\n+/, '')}`);
  if (!existsSync(path)) {
    drift.push(`missing: ${local}`);
    return;
  }
  const actual = await readFile(path, 'utf8');
  if (actual !== expected) {
    drift.push(`drift: ${local}`);
  }
}

/* ------------------------------------------------------------------ */
/* CLI                                                                */
/* ------------------------------------------------------------------ */

async function main() {
  const check = process.argv.includes('--check');
  if (check) {
    const drift = await checkFreshness();
    if (drift.length > 0) {
      console.error(
        `Admin codegen freshness check failed:\n${drift.map((item) => `- ${item}`).join('\n')}`,
      );
      process.exitCode = 1;
      return;
    }
    console.log('Admin codegen is fresh.');
    return;
  }
  const result = await generateAll();
  console.log(
    `Admin codegen generated: ${result.plugins.length} plugins, ${result.routes.length} routes.`,
  );
}

await main();
