/**
 * admin-codegen —— 确定性 Admin Surface Codegen 工具（Architecture Gate 执行点）。
 *
 * 职责边界：
 * - Discovery：扫描 surfaces/admin/plugins/ 下各 plugin 的 plugin.ts 与 routes 树
 *   （每个路由目录一对 page 文件与 route.meta 文件）。
 * - Contract Validation：静态校验 1:1 配对、禁止 Next exports、namespace、override、冲突；
 *   navigation.groupId 必须命中 Admin Surface taxonomy（单一 authority：
 *   surfaces/admin/src/navigation-taxonomy.ts），未知分组 deterministic fail；
 *   navigation.iconId（可选 semantic presentation metadata）必须命中 Admin Surface
 *   icon vocabulary（单一 authority：surfaces/admin/src/navigation-icon.ts），
 *   未知 iconId deterministic fail（UNKNOWN_ADMIN_NAVIGATION_ICON），禁止静默 fallback。
 * - Framework Descriptors：只生成静态 descriptors / catalog / bridges / composition / i18n。
 * - Host Capability Analysis：Static Export Host 对 [param] 路由返回
 *   UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE，不生成 Next 入口并令 gate 失败（硬失败、不降级）。
 * - Preflighted Deterministic Reconciliation：先完成全部 semantic / Host capability /
 *   taxonomy validation，并在内存中渲染全部 ExpectedArtifact（kind/path/content），
 *   再做物理 ownership preflight（期望 Host artifact 已存在且不属于本 Generator →
 *   Host artifact ownership collision，deterministic fail）。
 *   只有全部通过后才执行 mutation：rm/rewrite generatedRoot → create/update Host
 *   artifacts → delete stale owned artifacts → prune 空目录。
 *   保证：deterministic failure before mutation / no partial output for preflight failures。
 *   本工具不提供 mutation 开始后的 OS/IO/process interruption staging/transaction
 *   commit/rollback，不声称 filesystem-level atomicity。
 *
 * Registry（canonical hierarchy / navigation inheritance / breadcrumb / command / permission）
 * 由 @community-go/admin-framework registry 在运行时完成，Generator 不复制该逻辑。
 *
 * 本工具不执行 React 代码；route.meta.ts 与 navigation-taxonomy.ts 通过 Node 24
 * type-stripping 静态加载。生成物全部带固定 `GENERATED_HEADER`（ownership marker 单一
 * 来源，emission 与 ownership parser 共享）；freshness check 逐文件重建比较
 * （missing / drift / stale / ownership collision）。
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const frontendRoot = resolve(import.meta.dirname, '..', '..');
const surfaceRoot = join(frontendRoot, 'surfaces', 'admin');
const pluginsRoot = join(surfaceRoot, 'plugins');
const generatedRoot = join(surfaceRoot, 'generated');
const hostAppRoot = join(frontendRoot, 'apps', 'admin-web', 'src', 'app');
const surfacePackageName = '@community-go/admin-surface';
const surfaceTaxonomyPath = join(surfaceRoot, 'src', 'navigation-taxonomy.ts');
const surfaceIconVocabularyPath = join(surfaceRoot, 'src', 'navigation-icon.ts');

/**
 * Generator ownership header（单一来源）。
 *
 * emission（写出的每个 artifact 首行）与 ownership parser（isGeneratorOwned）
 * 共用本常量，二者不可能漂移。首行与 GENERATED_HEADER 严格相等即判定 owned。
 */
export const GENERATED_HEADER =
  '// @generated by tooling/admin-codegen —— 不要手改，运行 `pnpm codegen:admin` 重新生成。';

/** 本 Generator 负责的 Host adapter 类型（当前只生成 page；未来 layout/loading/error 同机制覆盖）。 */
const HOST_ADAPTER_KINDS = ['page'];

/** 磁盘 actual artifact 是否归 admin-plugin-codegen 所有：首个有效行与 GENERATED_HEADER 严格相等。 */
export function isGeneratorOwned(content) {
  for (const line of content.split(/\r?\n/)) {
    if (line.trim() === '') continue;
    return line === GENERATED_HEADER;
  }
  return false;
}

/** 文件名是否属于某 Host adapter kind 的候选（如 page.tsx / page.ts）。 */
function isHostAdapterCandidateFileName(name) {
  return HOST_ADAPTER_KINDS.some((kind) => name === `${kind}.tsx` || name === `${kind}.ts`);
}

/* ------------------------------------------------------------------ */
/* Small helpers                                                       */
/* ------------------------------------------------------------------ */

async function exists(path) {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function walk(directory) {
  if (!existsSync(directory)) return [];
  const files = [];
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(fullPath)));
    else files.push(fullPath);
  }
  return files;
}

function toPosix(path) {
  return path.split(sep).join('/');
}

async function loadTypeScriptModule(path) {
  return import(pathToFileURL(path).href);
}

function escapeIdentifier(name) {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

/** routeId → generated bridge 文件名（无扩展）。 */
function bridgeFileName(routeId) {
  return escapeIdentifier(routeId);
}

/** routeId → Host 薄入口内的 bridge export 名。 */
function hostBridgeExportName(route) {
  return `AdminRouteBridge_${bridgeFileName(route.descriptor.routeId)}`;
}

/* ------------------------------------------------------------------ */
/* Discovery                                                           */
/* ------------------------------------------------------------------ */

export async function discoverSurface() {
  const plugins = [];
  for (const entry of await readdir(pluginsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pluginDir = join(pluginsRoot, entry.name);
    const manifestPath = join(pluginDir, 'plugin.ts');
    if (!(await exists(manifestPath))) continue;
    const manifestModule = await loadTypeScriptModule(manifestPath);
    const definition = manifestModule?.pluginDefinition;
    if (!definition?.pluginId || !definition?.mount) {
      throw new Error(`plugins/${entry.name}/plugin.ts 缺少合法 pluginDefinition`);
    }
    const i18nPath = join(pluginDir, 'i18n.ts');
    plugins.push({
      definition,
      dir: pluginDir,
      hasI18n: await exists(i18nPath),
    });
  }
  return [...plugins].sort((a, b) => a.definition.pluginId.localeCompare(b.definition.pluginId));
}

/* ------------------------------------------------------------------ */
/* Validation                                                          */
/* ------------------------------------------------------------------ */

const forbiddenPageExports = [
  'generateStaticParams',
  'generateMetadata',
  'generateViewport',
  'revalidate',
  'dynamic',
  'runtime',
  'preferredRegion',
  'fetchCache',
  'maxDuration',
  'dynamicParams',
];

function forbiddenPageExportFound(content) {
  return forbiddenPageExports.filter((name) => {
    const pattern = new RegExp(
      `export\\s+(?:const|let|function)\\s+${name}\\b|export\\s*\\{\\s*${name}\\b`,
    );
    return pattern.test(content);
  });
}

/** 解析 Plugin Page 的具名组件导出；确定性：全文件必须恰好导出一个组件函数。 */
async function resolvePageComponent(pagePath) {
  const content = await readFile(pagePath, 'utf8');
  const exports = [];
  const namedFunction = /export\s+function\s+([A-Za-z_$][\w$]*)\s*\(/g;
  for (const match of content.matchAll(namedFunction)) exports.push(match[1]);
  // export default function Name 也视为组件
  const defaultFunction = /export\s+default\s+function\s+([A-Za-z_$][\w$]*)\s*\(/;
  const defaultMatch = defaultFunction.exec(content);
  if (defaultMatch) exports.push(defaultMatch[1]);
  if (exports.length !== 1) {
    throw new Error(
      `${pagePath}: Plugin Page 必须恰好导出一个具名组件函数（找到 ${exports.length} 个：${exports.join(', ') || '无'}）`,
    );
  }
  return exports[0];
}

async function scanRoutesTree(plugin) {
  const routesDir = join(plugin.dir, 'routes');
  if (!existsSync(routesDir)) return [];
  const files = await walk(routesDir);
  const pageByDir = new Map();
  const metaByDir = new Map();
  for (const file of files) {
    const local = toPosix(relative(routesDir, file));
    const isPage = /page\.tsx?$/.test(local);
    const isMeta = local.endsWith('route.meta.ts');
    if (!isPage && !isMeta) continue;
    const dir = local.includes('/') ? local.slice(0, local.lastIndexOf('/')) : '';
    if (isPage) pageByDir.set(dir, file);
    if (isMeta) metaByDir.set(dir, file);
  }

  for (const dir of metaByDir.keys()) {
    if (!pageByDir.has(dir)) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: route.meta.ts 缺少 1:1 的 page.tsx`,
      );
    }
  }
  for (const dir of pageByDir.keys()) {
    if (!metaByDir.has(dir)) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: page.tsx 缺少 1:1 的 route.meta.ts`,
      );
    }
  }

  const routes = [];
  for (const dir of [...pageByDir.keys()].sort()) {
    const pagePath = pageByDir.get(dir);
    const metaPath = metaByDir.get(dir);
    for (const segment of dir === '' ? [] : dir.split('/')) {
      if (
        segment.includes('...') ||
        segment.startsWith('(') ||
        segment.startsWith('@') ||
        /^\[\[.+]]$/.test(segment)
      ) {
        throw new Error(
          `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: 禁止 catch-all、parallel、route group（${segment}）`,
        );
      }
    }
    const pageContent = await readFile(pagePath, 'utf8');
    const forbidden = forbiddenPageExportFound(pageContent);
    if (forbidden.length > 0) {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: 禁止 Next 专用导出 ${forbidden.join(', ')}`,
      );
    }
    const metaModule = await loadTypeScriptModule(metaPath);
    const routeMeta = metaModule?.routeMeta;
    if (!routeMeta || typeof routeMeta !== 'object') {
      throw new Error(
        `plugins/${plugin.definition.pluginId}/routes/${dir || '.'}: route.meta.ts 必须导出 routeMeta`,
      );
    }
    const componentExport = await resolvePageComponent(pagePath);
    const descriptor = buildDescriptor(plugin, dir, routeMeta);
    validateRouteMetaContract(plugin, dir, descriptor, routeMeta);
    routes.push({ dir, pagePath, metaPath, descriptor, componentExport });
  }
  return [...routes].sort((a, b) => a.descriptor.routeId.localeCompare(b.descriptor.routeId));
}

function buildDescriptor(plugin, relativeDir, routeMeta) {
  const pluginId = plugin.definition.pluginId;
  const segments = relativeDir === '' ? [] : relativeDir.split('/');
  const routeId = relativeDir === '' ? pluginId : `${pluginId}.${relativeDir.split('/').join('.')}`;
  const pattern =
    segments.length === 0
      ? plugin.definition.mount
      : `${plugin.definition.mount}/${segments.join('/')}`;
  const paramNames = segments
    .filter((segment) => /^\[[A-Za-z0-9_]+]$/.test(segment))
    .map((segment) => segment.slice(1, -1));

  const navigation = routeMeta.navigation;
  return {
    routeId,
    pluginId,
    path: segments.join('/'),
    segments,
    pattern,
    paramNames,
    hasNavigation: Boolean(navigation),
    ...(navigation?.navigationId ? { navigationId: navigation.navigationId } : {}),
    ...(navigation?.labelKey ? { labelKey: navigation.labelKey } : {}),
    ...(navigation?.groupId ? { groupId: navigation.groupId } : {}),
    ...(navigation?.iconId ? { iconId: navigation.iconId } : {}),
    ...(routeMeta.titleKey ? { titleKey: routeMeta.titleKey } : {}),
    ...(routeMeta.canonicalParentOverride
      ? { canonicalParentOverride: routeMeta.canonicalParentOverride }
      : {}),
    ...(routeMeta.activeNavigationOverride
      ? { activeNavigationOverride: routeMeta.activeNavigationOverride }
      : {}),
    ...(routeMeta.permissions?.length ? { permissions: routeMeta.permissions } : {}),
  };
}

function validateRouteMetaContract(plugin, relativeDir, descriptor, routeMeta) {
  const errors = [];
  const pluginId = plugin.definition.pluginId;
  if (routeMeta.navigation) {
    if (typeof routeMeta.navigation.navigationId !== 'string') {
      errors.push('navigation.navigationId 必须提供');
    } else if (
      routeMeta.navigation.navigationId !== pluginId &&
      !routeMeta.navigation.navigationId.startsWith(`${pluginId}.`)
    ) {
      errors.push(`navigation.navigationId 必须为 ${pluginId}.* namespace`);
    }
    if (typeof routeMeta.navigation.labelKey !== 'string' || !routeMeta.navigation.labelKey) {
      errors.push('navigation.labelKey 必须提供');
    }
    if (typeof routeMeta.navigation.groupId !== 'string' || !routeMeta.navigation.groupId) {
      errors.push('navigation.groupId 必须提供');
    }
  }
  if (routeMeta.canonicalParentOverride) {
    const override = routeMeta.canonicalParentOverride;
    if (typeof override.routeId !== 'string' || override.routeId.split('.')[0] !== pluginId) {
      errors.push('canonicalParentOverride.routeId 必须引用同 Plugin Route');
    }
    if (typeof override.rationale !== 'string' || !override.rationale.trim()) {
      errors.push('canonicalParentOverride 必须提供 rationale');
    }
  }
  if (routeMeta.activeNavigationOverride) {
    const override = routeMeta.activeNavigationOverride;
    if (
      typeof override.navigationId !== 'string' ||
      override.navigationId.split('.')[0] !== pluginId
    ) {
      errors.push('activeNavigationOverride.navigationId 必须为同 Plugin namespace');
    }
    if (typeof override.rationale !== 'string' || !override.rationale.trim()) {
      errors.push('activeNavigationOverride 必须提供 rationale');
    }
  }
  if (errors.length > 0) {
    throw new Error(
      `plugins/${pluginId}/routes/${relativeDir || '.'}: metadata 契约失败\n${errors.map((item) => `- ${item}`).join('\n')}`,
    );
  }
}

function validateCatalogConflicts(allRoutes, plugins) {
  const routeIds = new Set();
  const patterns = new Set();
  const mounts = new Set();
  const errors = [];
  for (const route of allRoutes) {
    if (routeIds.has(route.descriptor.routeId)) {
      errors.push(`重复 routeId: ${route.descriptor.routeId}`);
    }
    routeIds.add(route.descriptor.routeId);
    if (patterns.has(route.descriptor.pattern)) {
      errors.push(`重复 pattern: ${route.descriptor.pattern}`);
    }
    patterns.add(route.descriptor.pattern);
  }
  for (const plugin of plugins) {
    if (mounts.has(plugin.definition.mount)) {
      errors.push(`mount 冲突: ${plugin.definition.mount}`);
    }
    mounts.add(plugin.definition.mount);
  }
  if (errors.length > 0) {
    throw new Error(`Catalog 冲突:\n${errors.map((item) => `- ${item}`).join('\n')}`);
  }
}

/**
 * Navigation taxonomy gate：声明 navigation 的 route 的 groupId 必须命中
 * Admin Surface taxonomy（单一 authority：navigation-taxonomy.ts）。
 * 未知分组 deterministic fail，禁止 silent drop。
 */
async function validateNavigationGroupReferences(allRoutes) {
  const taxonomyModule = await loadTypeScriptModule(surfaceTaxonomyPath);
  const collect = taxonomyModule?.collectUnknownNavigationGroupDiagnostics;
  if (typeof collect !== 'function') {
    throw new Error('无法加载 Admin Surface taxonomy authority（navigation-taxonomy.ts）');
  }
  const references = allRoutes
    .filter((route) => route.descriptor.hasNavigation && route.descriptor.groupId)
    .map((route) => ({
      groupId: route.descriptor.groupId,
      routeId: route.descriptor.routeId,
    }));
  const diagnostics = collect(references);
  if (diagnostics.length > 0) {
    throw new Error(
      `Navigation taxonomy gate 失败 (${diagnostics[0].code}):\n${diagnostics
        .map((diagnostic) => `- [${diagnostic.code}] ${diagnostic.message}`)
        .join('\n')}`,
    );
  }
}

/**
 * Navigation icon vocabulary gate：声明 navigation 且带 iconId 的 route，其 iconId
 * 必须命中 Admin Surface icon vocabulary（单一 authority：navigation-icon.ts）。
 * iconId 是可选 semantic presentation metadata；未知 iconId deterministic fail，
 * 禁止静默 fallback 掩盖配置错误。
 */
async function validateNavigationIconReferences(allRoutes) {
  const iconModule = await loadTypeScriptModule(surfaceIconVocabularyPath);
  const collect = iconModule?.collectUnknownNavigationIconDiagnostics;
  if (typeof collect !== 'function') {
    throw new Error('无法加载 Admin Surface icon vocabulary authority（navigation-icon.ts）');
  }
  const references = allRoutes
    .filter((route) => route.descriptor.hasNavigation && route.descriptor.iconId)
    .map((route) => ({
      iconId: route.descriptor.iconId,
      routeId: route.descriptor.routeId,
    }));
  const diagnostics = collect(references);
  if (diagnostics.length > 0) {
    throw new Error(
      `Navigation icon vocabulary gate 失败 (${diagnostics[0].code}):\n${diagnostics
        .map((diagnostic) => `- [${diagnostic.code}] ${diagnostic.message}`)
        .join('\n')}`,
    );
  }
}

/**
 * discovery + 全部 deterministic semantic validation。
 * generateAll 与 checkFreshness 共用同一校验链，保证两入口规则一致。
 */
async function collectSurface() {
  const plugins = await discoverSurface();
  const collected = [];
  for (const plugin of plugins) {
    collected.push({ plugin, routes: await scanRoutesTree(plugin) });
  }
  const allRoutes = collected.flatMap((item) => item.routes);
  validateCatalogConflicts(allRoutes, plugins);
  await validateNavigationGroupReferences(allRoutes);
  await validateNavigationIconReferences(allRoutes);
  const dynamic = allRoutes.filter((route) => route.descriptor.paramNames.length > 0);
  if (dynamic.length > 0) {
    throw new Error(
      `Host capability gate 失败 (UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE): Static Export Host 不支持动态 Plugin Route\n${dynamic
        .map((route) => `- ${route.descriptor.routeId} (${route.descriptor.pattern})`)
        .join('\n')}`,
    );
  }
  return { plugins, allRoutes };
}

/* ------------------------------------------------------------------ */
/* Text builders（emission 与 freshness 共用同一文本生成，保证确定一致） */
/* ------------------------------------------------------------------ */

function buildCatalogText(plugins, allRoutes) {
  const lines = [
    "import type { AdminRouteCatalog } from '@community-go/admin-framework';",
    '',
    'export const generatedRouteCatalog: AdminRouteCatalog = {',
    '  plugins: [',
  ];
  for (const plugin of plugins) {
    lines.push(
      `    { pluginId: ${JSON.stringify(plugin.definition.pluginId)}, mount: ${JSON.stringify(plugin.definition.mount)} },`,
    );
  }
  lines.push('  ],');
  lines.push('  routes: [');
  for (const route of allRoutes) {
    lines.push('    {');
    for (const [key, value] of Object.entries(route.descriptor)) {
      if (value === undefined || value === null) continue;
      lines.push(`      ${key}: ${JSON.stringify(value)},`);
    }
    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('};');
  return `${lines.join('\n')}\n`;
}

function buildCompositionText(plugins) {
  const i18nPlugins = plugins.filter((plugin) => plugin.hasI18n);
  const lines = [
    "import { createAdminRegistry } from '@community-go/admin-framework';",
    "import type { AdminRegistryModel } from '@community-go/admin-framework';",
    "import type { TranslationResources } from '@community-go/i18n';",
    "import { generatedRouteCatalog } from '../catalog/catalog';",
    "import { assertValidAdminSurfaceRegistry, mergeTranslationResources, type AdminSurfaceComposition } from '../../src/composition';",
    "import { surfaceShellI18nResources } from '../../src/i18n';",
    ...i18nPlugins.map(
      (plugin) =>
        `import { pluginI18nResources as pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)} } from '../../plugins/${plugin.definition.pluginId}/i18n';`,
    ),
    '',
    'export const generatedSurfaceRegistry: AdminRegistryModel =',
    '  createAdminRegistry(generatedRouteCatalog);',
    '',
    '// Surface composition/model boundary runtime invariant：navigation group 必须命中 Admin Surface taxonomy。',
    'assertValidAdminSurfaceRegistry(generatedSurfaceRegistry);',
    '',
    'export const generatedSurfaceI18nResources: TranslationResources = mergeTranslationResources(',
    '  surfaceShellI18nResources,',
    ...i18nPlugins.map(
      (plugin) => `  pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)},`,
    ),
    ');',
    '',
    'export const generatedAdminSurfaceComposition: AdminSurfaceComposition = {',
    '  registryModel: generatedSurfaceRegistry,',
    '  i18nResources: generatedSurfaceI18nResources,',
    '};',
    '',
  ];
  return lines.join('\n');
}

function buildBridgeText(route) {
  const pageSpecifier = toPosix(
    relative(join(generatedRoot, 'routes'), route.pagePath).replace(/\.tsx?$/, ''),
  );
  return [
    "'use client';",
    '',
    "import { AdminRouteContextProvider } from '@community-go/admin-framework/route-context';",
    `import { ${route.componentExport} } from ${JSON.stringify(pageSpecifier)};`,
    '',
    'export default function AdminRouteBridge({',
    '  params,',
    '}: Readonly<{ params: Readonly<Record<string, string>> }>) {',
    '  return (',
    '    <AdminRouteContextProvider',
    `      value={{ routeId: ${JSON.stringify(route.descriptor.routeId)}, params }}`,
    '    >',
    `      <${route.componentExport} />`,
    '    </AdminRouteContextProvider>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function bridgeImportSpecifier(route) {
  return `${surfacePackageName}/generated/routes/${bridgeFileName(route.descriptor.routeId)}`;
}

function buildHostEntryText(route) {
  return [
    `import ${hostBridgeExportName(route)} from ${JSON.stringify(bridgeImportSpecifier(route))};`,
    '',
    '// 薄入口：await Next params Promise 后转发稳定 params，保持 Route Context 发布与 Host 边界。',
    'export default async function AdminRouteEntry({',
    '  params,',
    '}: Readonly<{ params: Promise<Readonly<Record<string, string>>> }>) {',
    '  const resolvedParams = await params;',
    `  return <${hostBridgeExportName(route)} params={resolvedParams} />;`,
    '}',
    '',
  ].join('\n');
}

function hostEntryPath(route) {
  return join(hostAppRoot, route.descriptor.pattern.replace(/^\//, ''), 'page.tsx');
}

async function ensureDir(path) {
  await mkdir(dirname(path), { recursive: true });
}

/** Prettier 格式化生成的文本（与 repo 根配置一致），保证 deterministic emission 与 format:check 同时通过。 */
async function formatCode(path, content) {
  const config = await prettier.resolveConfig(path);
  const parser = /\.(?:ts|tsx)$/.test(path) ? 'typescript' : 'babel';
  return prettier.format(content, { ...config, parser });
}

/** 渲染最终可写内容：固定 ownership header + prettier 格式化。 */
async function renderFinalContent(path, content) {
  return formatCode(path, `${GENERATED_HEADER}\n\n${content.replace(/^\n+/, '')}`);
}

/* ------------------------------------------------------------------ */
/* Expected artifact plan（渲染阶段：纯内存，无文件系统写入）            */
/* ------------------------------------------------------------------ */

/**
 * 构建完整 expected artifact plan（{ kind, path, content }）。
 *
 * catalog / composition / i18n index / route bridge / Host adapter 的全部文本
 * 构造与 prettier 格式化都在此完成——任何可能抛错的 render/serialization 都会在
 * mutation 之前暴露（validation-before-write / no partial output）。
 */
async function buildExpectedArtifacts(plugins, allRoutes) {
  const artifacts = [];
  const pushGenerated = async (local, text) => {
    const path = join(generatedRoot, local);
    artifacts.push({
      kind: 'generated-file',
      path,
      content: await renderFinalContent(path, text),
    });
  };
  await pushGenerated('catalog/catalog.ts', buildCatalogText(plugins, allRoutes));
  await pushGenerated('composition/composition.ts', buildCompositionText(plugins));
  await pushGenerated(
    'composition/i18n.ts',
    "export { generatedSurfaceI18nResources } from './composition';\n",
  );
  for (const route of allRoutes) {
    await pushGenerated(
      `routes/${bridgeFileName(route.descriptor.routeId)}.tsx`,
      buildBridgeText(route),
    );
    const entryPath = hostEntryPath(route);
    artifacts.push({
      kind: 'host-adapter',
      path: entryPath,
      content: await renderFinalContent(entryPath, buildHostEntryText(route)),
    });
  }
  return artifacts;
}

/* ------------------------------------------------------------------ */
/* Mutation / reconciliation                                          */
/* ------------------------------------------------------------------ */

/** 删除空目录（自下而上，不越过 hostAppRoot）。 */
async function pruneEmptyDirs(startDir) {
  let current = startDir;
  while (current !== hostAppRoot && current.startsWith(hostAppRoot + sep)) {
    let entries;
    try {
      entries = await readdir(current, { withFileTypes: true });
    } catch {
      break;
    }
    const meaningful = entries.filter(
      (entry) => !entry.name.startsWith('.') && entry.name !== 'node_modules',
    );
    if (meaningful.length > 0) break;
    const parent = dirname(current);
    await rm(current, { recursive: true, force: true });
    current = parent;
  }
}

/**
 * 执行 reconciliation（仅在全部 validation + preflight 通过后调用）：
 * rm/rewrite generatedRoot → create/update Host artifacts → delete stale owned
 * artifacts → prune 空目录。
 */
async function reconcileArtifacts(artifacts) {
  const expectedHostPaths = new Set(
    artifacts
      .filter((artifact) => artifact.kind === 'host-adapter')
      .map((artifact) => artifact.path),
  );

  // 1. generatedRoot：整树归本 Generator 所有（既有契约），rm + 重写。
  await rm(generatedRoot, { recursive: true, force: true });
  for (const artifact of artifacts) {
    if (artifact.kind !== 'generated-file') continue;
    await ensureDir(artifact.path);
    await writeFile(artifact.path, artifact.content);
  }

  // 2. Host adapter artifacts：create/update（ownership 已在 preflight 保证）。
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    await ensureDir(artifact.path);
    await writeFile(artifact.path, artifact.content);
  }

  // 3. delete stale generator-owned Host artifacts + prune 空目录。
  const removed = [];
  for (const file of await walk(hostAppRoot)) {
    if (!isHostAdapterCandidateFileName(basename(file))) continue;
    if (expectedHostPaths.has(file)) continue;
    const content = await readFile(file, 'utf8');
    if (!isGeneratorOwned(content)) continue;
    await rm(file, { force: true });
    removed.push(file);
  }
  for (const file of removed) {
    await pruneEmptyDirs(dirname(file));
  }
}

/* ------------------------------------------------------------------ */
/* Freshness check                                                     */
/* ------------------------------------------------------------------ */

async function checkFreshness() {
  const { plugins, allRoutes } = await collectSurface();
  const artifacts = await buildExpectedArtifacts(plugins, allRoutes);
  const drift = [];

  const expectedGeneratedPaths = new Set();
  for (const artifact of artifacts) {
    if (artifact.kind !== 'generated-file') continue;
    expectedGeneratedPaths.add(artifact.path);
    const local = `surfaces/admin/generated/${toPosix(relative(generatedRoot, artifact.path))}`;
    if (!existsSync(artifact.path)) {
      drift.push(`missing: ${local}`);
      continue;
    }
    const actual = await readFile(artifact.path, 'utf8');
    if (actual !== artifact.content) {
      drift.push(`drift: ${local}`);
    }
  }
  // stale generated file：generated 目录中存在但不再期望的文件
  for (const file of await walk(generatedRoot)) {
    if (!expectedGeneratedPaths.has(file)) {
      drift.push(
        `stale generated file: surfaces/admin/generated/${toPosix(relative(generatedRoot, file))}`,
      );
    }
  }

  const expectedHostPaths = new Set();
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    expectedHostPaths.add(artifact.path);
    const local = toPosix(relative(frontendRoot, artifact.path));
    if (!existsSync(artifact.path)) {
      drift.push(`missing: ${local}`);
      continue;
    }
    const actual = await readFile(artifact.path, 'utf8');
    if (!isGeneratorOwned(actual)) {
      drift.push(
        `host artifact ownership collision: ${local}（已存在且不属于 admin-plugin-codegen）`,
      );
    } else if (actual !== artifact.content) {
      drift.push(`drift: ${local}`);
    }
  }
  // stale generator-owned Host artifact：通用扫描（无具体插件特判）
  for (const file of await walk(hostAppRoot)) {
    if (!isHostAdapterCandidateFileName(basename(file))) continue;
    if (expectedHostPaths.has(file)) continue;
    const content = await readFile(file, 'utf8');
    if (isGeneratorOwned(content)) {
      drift.push(`stale generator-owned host artifact: ${toPosix(relative(frontendRoot, file))}`);
    }
  }

  return drift;
}

/* ------------------------------------------------------------------ */
/* CLI                                                                */
/* ------------------------------------------------------------------ */

async function main() {
  const check = process.argv.includes('--check');
  if (check) {
    const drift = await checkFreshness();
    if (drift.length > 0) {
      console.error(
        `Admin codegen freshness check failed:\n${drift.map((item) => `- ${item}`).join('\n')}`,
      );
      process.exitCode = 1;
      return;
    }
    console.log('Admin codegen is fresh.');
    return;
  }
  const { plugins, allRoutes } = await collectSurface();
  const artifacts = await buildExpectedArtifacts(plugins, allRoutes);

  // Physical ownership preflight：期望 Host artifact 已存在且不属于本 Generator
  // → deterministic fail。此时尚未发生任何文件系统 mutation。
  const collisions = [];
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    if (!existsSync(artifact.path)) continue;
    const actual = await readFile(artifact.path, 'utf8');
    if (!isGeneratorOwned(actual)) {
      collisions.push(toPosix(relative(frontendRoot, artifact.path)));
    }
  }
  if (collisions.length > 0) {
    throw new Error(
      `Host artifact ownership collision（preflight 失败，未写入/删除任何文件）:\n${collisions
        .map((path) => `- ${path}`)
        .join('\n')}`,
    );
  }

  await reconcileArtifacts(artifacts);
  console.log(`Admin codegen generated: ${plugins.length} plugins, ${allRoutes.length} routes.`);
}

await main();
