/**
 * admin-codegen —— 确定性 Admin Surface Codegen 工具（Architecture Gate 执行点）。
 *
 * 职责边界：
 * - Discovery：扫描 surfaces/admin/plugins/ 下各 plugin 的 plugin.ts、plugin.navigation.ts
 *   与 routes 子树，并加载 plugins 范围公共 Group Alias（navigation-groups.ts）。
 * - Contract Validation：静态校验 pluginId/mount、冲突、namespace、Group Alias 与
 *   icon vocabulary；contribution parent 的 groupId 必须命中 Group Alias（plugins 公共
 *   IA，未知 Alias deterministic fail）；navigation.iconId（可选 semantic presentation
 *   metadata）必须命中 Admin Surface icon vocabulary（surfaces/admin/src/navigation-icon.ts），
 *   未知 iconId deterministic fail（UNKNOWN_ADMIN_NAVIGATION_ICON），禁止静默 fallback。
 * - Framework Descriptors：只生成静态 descriptors（pluginId + Next 文件树派生）/ aliases /
 *   contributions / catalog / shims / composition / i18n。routes/ 的 authority 是 Next
 *   App Router：colocated 普通实现文件完全忽略；当前支持的 Next convention
 *   （page/layout/template/loading/error/not-found）机械装配；Next 有语义但当前不装配的
 *   convention（route.ts/default.tsx）报 UNSUPPORTED_NEXT_CONVENTION（Host capability
 *   诊断，非 Plugin Contract 禁止）。
 * - Host Capability Analysis：Static Export Host 对 [param] 路由返回
 *   UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE，不生成 Host adapter 并令 gate 失败（硬失败、不降级）。
 * - Preflighted Deterministic Reconciliation：先完成全部 semantic / Host capability /
 *   Alias/icon validation，并在内存中渲染全部 ExpectedArtifact（kind/path/content），
 *   再做物理 ownership preflight（期望 Host artifact 已存在且不属于本 Generator →
 *   Host artifact ownership collision，deterministic fail）。
 *   只有全部通过后才执行 mutation：rm/rewrite generatedRoot → create/update Host
 *   artifacts → delete stale owned artifacts → prune 空目录。
 *   保证：deterministic failure before mutation / no partial output for preflight failures。
 *   本工具不提供 mutation 开始后的 OS/IO/process interruption staging/transaction
 *   commit/rollback，不声称 filesystem-level atomicity。
 *
 * Registry（Sidebar Group→Parent→Child resolution）由 @community-go/admin-framework
 * registry 在运行时完成，Generator 不复制该逻辑，只序列化静态 aliases/contributions。
 * Framework 不平行建模 Next Route Tree：routeId→descriptor 只是 Plugin 管理功能
 * （Navigation target 校验、Route Target、冲突诊断）需要的 Page Route 索引。
 *
 * 本工具不执行 React 代码；plugin.navigation.ts 与 navigation-groups.ts 通过 Node 24
 * type-stripping 静态加载。生成物全部带固定 `GENERATED_HEADER`（ownership marker
 * 单一来源，emission 与 ownership parser 共享）；freshness check 逐文件重建比较
 * （missing / drift / stale / ownership collision）。
 */

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';

const frontendRoot = resolve(import.meta.dirname, '..', '..');
const surfaceRoot = join(frontendRoot, 'surfaces', 'admin');
const pluginsRoot = join(surfaceRoot, 'plugins');
const generatedRoot = join(surfaceRoot, 'generated');
const hostAppRoot = join(frontendRoot, 'apps', 'admin-web', 'src', 'app');
const surfacePackageName = '@community-go/admin-surface';
const navigationGroupsPath = join(pluginsRoot, 'navigation-groups.ts');
const surfaceIconVocabularyPath = join(surfaceRoot, 'src', 'navigation-icon.ts');

/* ------------------------------------------------------------------ */
/* 构建期配置（轻量 .env 加载，零依赖）                                  */
/* ------------------------------------------------------------------ */

/**
 * 从 frontend 根 .env 加载配置进 process.env（若尚未设置）。
 *
 * codegen 是独立 Node CLI（不在 Next 进程内），Node 不会自动读 .env；这里做最小
 * 自解析：只读 frontend/.env，跳过注释与空行，支持 KEY=VALUE（值不去引号、不展开）。
 * 已存在的 process.env 优先（不覆盖），保证显式环境变量/CI 可覆盖 .env。
 */
export function loadFrontendEnv() {
  const envPath = join(frontendRoot, '.env');
  if (!existsSync(envPath)) return;
  let content;
  try {
    content = readFileSync(envPath, 'utf8');
  } catch {
    return;
  }
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (!key || process.env[key] !== undefined) continue;
    process.env[key] = value;
  }
}

/** 是否启用 Plugin 动态路由（[id] 等）——默认 false（默认静态）。 */
export function isDynamicRoutesEnabled() {
  return process.env.ADMIN_SURFACE_DYNAMIC_ROUTES === 'true';
}

loadFrontendEnv();

/**
 * Generator ownership header（单一来源）。
 *
 * emission（写出的每个 artifact 首行）与 ownership parser（isGeneratorOwned）
 * 共用本常量，二者不可能漂移。首行与 GENERATED_HEADER 严格相等即判定 owned。
 */
export const GENERATED_HEADER =
  '// @generated by tooling/admin-codegen —— 不要手改，运行 `pnpm codegen:admin` 重新生成。';

/** 本 Generator 负责的 Host adapter 类型（Next special file 全 kind）。 */
const HOST_ADAPTER_KINDS = ['page', 'layout', 'template', 'loading', 'error', 'not-found'];

/** Next special file 名（不含扩展）。 */
const NEXT_SPECIAL_FILES = new Set(HOST_ADAPTER_KINDS);

/** 磁盘 actual artifact 是否归 admin-plugin-codegen 所有：首个有效行与 GENERATED_HEADER 严格相等。 */
export function isGeneratorOwned(content) {
  for (const line of content.split(/\r?\n/)) {
    if (line.trim() === '') continue;
    return line === GENERATED_HEADER;
  }
  return false;
}

/** 文件名是否属于某 Host adapter kind 的候选（如 page.tsx / page.ts）。 */
function isHostAdapterCandidateFileName(name) {
  return HOST_ADAPTER_KINDS.some((kind) => name === `${kind}.tsx` || name === `${kind}.ts`);
}

/* ------------------------------------------------------------------ */
/* Small helpers                                                       */
/* ------------------------------------------------------------------ */

async function exists(path) {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function walk(directory) {
  if (!existsSync(directory)) return [];
  const files = [];
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(fullPath)));
    else files.push(fullPath);
  }
  return files;
}

function toPosix(path) {
  return path.split(sep).join('/');
}

async function loadTypeScriptModule(path) {
  return import(pathToFileURL(path).href);
}

function escapeIdentifier(name) {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

/* ------------------------------------------------------------------ */
/* Discovery                                                           */
/* ------------------------------------------------------------------ */

export async function discoverSurface() {
  const plugins = [];
  for (const entry of await readdir(pluginsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pluginDir = join(pluginsRoot, entry.name);
    const manifestPath = join(pluginDir, 'plugin.ts');
    if (!(await exists(manifestPath))) continue;
    const manifestModule = await loadTypeScriptModule(manifestPath);
    const definition = manifestModule?.pluginDefinition;
    if (!definition?.pluginId || !definition?.mount) {
      throw new Error(`plugins/${entry.name}/plugin.ts 缺少合法 pluginDefinition`);
    }
    const i18nPath = join(pluginDir, 'i18n.ts');
    const navigationPath = join(pluginDir, 'plugin.navigation.ts');
    let navigationContribution = null;
    if (await exists(navigationPath)) {
      const navModule = await loadTypeScriptModule(navigationPath);
      navigationContribution = navModule?.navigationContribution ?? null;
      if (!navigationContribution || typeof navigationContribution !== 'object') {
        throw new Error(
          `plugins/${entry.name}/plugin.navigation.ts 必须导出 navigationContribution`,
        );
      }
    }
    plugins.push({
      definition,
      dir: pluginDir,
      // 磁盘目录名：目录名不承担身份/URL 语义，只用于物理路径与错误定位；
      // 身份（pluginId/mount/routeId）一律取 plugin.ts 声明。
      dirName: entry.name,
      hasI18n: await exists(i18nPath),
      navigationContribution,
    });
  }
  return [...plugins].sort((a, b) => a.definition.pluginId.localeCompare(b.definition.pluginId));
}

/* ------------------------------------------------------------------ */
/* Validation                                                          */
/* ------------------------------------------------------------------ */

/**
 * Next 有语义、但当前 Generator/Host 尚不机械装配的 convention。
 *
 * authority 是 Next App Router 本身：本集合不是「Plugin routes/ 永久允许的全部 Next
 * 文件」白名单，只描述「当前支持的机械装配集」。将来扩展 route.ts / default.tsx /
 * metadata file conventions 等 = 扩大 Host capability（加入装配），不是修改 Plugin
 * Route Contract。发现此类文件必须给明确诊断，不能静默忽略。
 */
const NEXT_CONVENTIONS_NOT_ASSEMBLED = new Set(['route', 'default']);

/**
 * 扫描 Plugin routes/ 下的 Next special file 树（Page Route 索引）。
 *
 * - authority 是 Next App Router：Plugin routes/ 可像正常 app/ 一样 colocate 普通
 *   实现文件（components/services/lib/schema/styles/tests/_private 等），Framework
 *   完全忽略它们，不增加 Plugin 语义。
 * - 当前支持的 Next convention（page/layout/template/loading/error/not-found）机械装配；
 *   每段只要存在 page 就产出一条 Page Route（page 决定当前 Framework 所索引的可渲染
 *   Page Route；完整 Next Route Tree 由 Next 文件系统拥有）。
 * - Next 有语义但当前不装配的 convention（route.ts/default.tsx）→ Host Capability
 *   诊断，不静默忽略。
 */
async function scanRoutesTree(plugin) {
  const routesDir = join(plugin.dir, 'routes');
  if (!existsSync(routesDir)) return [];
  const files = await walk(routesDir);
  const filesByDir = new Map(); // dir → [{kind, file}]
  const unsupportedByDir = new Map(); // dir → [conventionName]
  for (const file of files) {
    const local = toPosix(relative(routesDir, file));
    const base = basename(file).replace(/\.tsx?$/, '');
    const dir = local.includes('/') ? local.slice(0, local.lastIndexOf('/')) : '';
    if (NEXT_SPECIAL_FILES.has(base)) {
      const list = filesByDir.get(dir) ?? [];
      list.push({ kind: base, file });
      filesByDir.set(dir, list);
      continue;
    }
    // Next 有语义但当前不装配的 convention：明确诊断，不静默忽略。
    if (NEXT_CONVENTIONS_NOT_ASSEMBLED.has(base)) {
      const list = unsupportedByDir.get(dir) ?? [];
      list.push(base);
      unsupportedByDir.set(dir, list);
    }
    // 其余文件（colocated components/services/lib/schema/styles/tests/_private 等）：
    // 普通实现文件，Framework 完全忽略。
  }

  // Host Capability 诊断：Next 语义文件当前 Host 不装配 → 显式报错（非 Plugin Contract 禁止）。
  for (const [dir, conventions] of unsupportedByDir) {
    throw new Error(
      `Host capability 诊断 (UNSUPPORTED_NEXT_CONVENTION): plugins/${plugin.dirName}/routes/${dir || '.'} 含 Next convention ${conventions.join(', ')} —— 当前 Generator/Host 尚未机械装配该 Next convention；这是 Host capability 限制，不是 Plugin Route Contract 禁止。`,
    );
  }

  const routes = [];
  for (const dir of [...filesByDir.keys()].sort()) {
    for (const segment of dir === '' ? [] : dir.split('/')) {
      if (
        segment.includes('...') ||
        segment.startsWith('(') ||
        segment.startsWith('@') ||
        /^\[\[.+]]$/.test(segment)
      ) {
        throw new Error(
          `plugins/${plugin.dirName}/routes/${dir || '.'}: 禁止 catch-all、parallel、route group（${segment}）`,
        );
      }
    }
    const entries = filesByDir.get(dir) ?? [];
    const page = entries.find((entry) => entry.kind === 'page');
    if (!page) continue; // 无 page 的段不产生 Page Route（colocate 目录/layout-only 容器不索引）
    const descriptor = buildDescriptor(plugin, dir);
    routes.push({
      dir,
      dirName: plugin.dirName,
      pagePath: page.file,
      descriptor,
      specialFiles: entries.map((entry) => entry.kind),
      // 动态 route 是否自带 generateStaticParams（静态导出 Host 放行动态的前提）。
      hasGenerateStaticParams: await pageExportsGenerateStaticParams(page.file),
    });
  }
  return [...routes].sort((a, b) => a.descriptor.routeId.localeCompare(b.descriptor.routeId));
}

/** 轻量静态检测 page 是否导出 generateStaticParams（不执行 React 代码）。 */
async function pageExportsGenerateStaticParams(pagePath) {
  const content = await readFile(pagePath, 'utf8');
  return (
    /export\s+(?:async\s+)?function\s+generateStaticParams\b/.test(content) ||
    /export\s+(?:const|let)\s+generateStaticParams\b/.test(content)
  );
}

/** 只从 pluginId + Next 文件树派生 Page Route identity（无任何逐 Route 声明文件）。 */
function buildDescriptor(plugin, relativeDir) {
  const pluginId = plugin.definition.pluginId;
  const segments = relativeDir === '' ? [] : relativeDir.split('/');
  const routeId = relativeDir === '' ? pluginId : `${pluginId}.${relativeDir.split('/').join('.')}`;
  const pattern =
    segments.length === 0
      ? plugin.definition.mount
      : `${plugin.definition.mount}/${segments.join('/')}`;
  const paramNames = segments
    .filter((segment) => /^\[[A-Za-z0-9_]+]$/.test(segment))
    .map((segment) => segment.slice(1, -1));

  return {
    routeId,
    pluginId,
    path: segments.join('/'),
    segments,
    pattern,
    paramNames,
  };
}

function validateCatalogConflicts(allRoutes, plugins) {
  const routeIds = new Set();
  const patterns = new Set();
  const mounts = new Set();
  const errors = [];
  for (const route of allRoutes) {
    if (routeIds.has(route.descriptor.routeId)) {
      errors.push(`重复 routeId: ${route.descriptor.routeId}`);
    }
    routeIds.add(route.descriptor.routeId);
    if (patterns.has(route.descriptor.pattern)) {
      errors.push(`重复 pattern: ${route.descriptor.pattern}`);
    }
    patterns.add(route.descriptor.pattern);
  }
  for (const plugin of plugins) {
    if (mounts.has(plugin.definition.mount)) {
      errors.push(`mount 冲突: ${plugin.definition.mount}`);
    }
    mounts.add(plugin.definition.mount);
  }
  if (errors.length > 0) {
    throw new Error(`Catalog 冲突:\n${errors.map((item) => `- ${item}`).join('\n')}`);
  }
}

/**
 * 加载 plugins 范围公共 Group Alias（navigation-groups.ts，单一 authority）。
 */
async function loadGroupAliases() {
  const module = await loadTypeScriptModule(navigationGroupsPath);
  const aliases = module?.adminNavigationGroupAliases;
  if (!Array.isArray(aliases)) {
    throw new Error('无法加载 Group Alias 公共契约（plugins/navigation-groups.ts）');
  }
  return aliases;
}

/**
 * Navigation Group Alias gate：每个 contribution parent 的 groupId 必须命中
 * plugins 范围 Group Alias（navigation-groups.ts）。未知 Alias deterministic fail，
 * 禁止 silent drop。
 */
async function validateGroupAliasReferences(plugins) {
  const aliases = await loadGroupAliases();
  const aliasIds = new Set(aliases.map((alias) => alias.groupId));
  const violations = [];
  for (const plugin of plugins) {
    const contribution = plugin.navigationContribution;
    if (!contribution) continue;
    for (const parent of contribution.parents ?? []) {
      if (!aliasIds.has(parent.groupId)) {
        violations.push(
          `[UNKNOWN_ADMIN_NAVIGATION_GROUP] ${plugin.definition.pluginId}: ${parent.navigationId} 引用不存在的 Group Alias: ${parent.groupId}`,
        );
      }
    }
  }
  if (violations.length > 0) {
    throw new Error(
      `Navigation Group Alias gate 失败:\n${violations.map((v) => `- ${v}`).join('\n')}`,
    );
  }
}

/**
 * Navigation icon vocabulary gate：contribution parent/child 的 iconId 必须命中
 * Admin Surface icon vocabulary（navigation-icon.ts，受控语义不动态化）。
 */
async function validateNavigationIconReferences(plugins) {
  const iconModule = await loadTypeScriptModule(surfaceIconVocabularyPath);
  const collect = iconModule?.collectUnknownNavigationIconDiagnostics;
  if (typeof collect !== 'function') {
    throw new Error('无法加载 Admin Surface icon vocabulary authority（navigation-icon.ts）');
  }
  const references = [];
  for (const plugin of plugins) {
    const contribution = plugin.navigationContribution;
    if (!contribution) continue;
    for (const parent of contribution.parents ?? []) {
      if (parent.iconId) {
        references.push({ iconId: parent.iconId, routeId: parent.navigationId });
      }
      for (const child of parent.children ?? []) {
        if (child.iconId) references.push({ iconId: child.iconId, routeId: child.navigationId });
      }
    }
  }
  const diagnostics = collect(references);
  if (diagnostics.length > 0) {
    throw new Error(
      `Navigation icon vocabulary gate 失败 (${diagnostics[0].code}):\n${diagnostics
        .map((diagnostic) => `- [${diagnostic.code}] ${diagnostic.message}`)
        .join('\n')}`,
    );
  }
}

/**
 * discovery + 全部 deterministic semantic validation。
 * generateAll 与 checkFreshness 共用同一校验链，保证两入口规则一致。
 */
async function collectSurface() {
  const plugins = await discoverSurface();
  const collected = [];
  for (const plugin of plugins) {
    collected.push({ plugin, routes: await scanRoutesTree(plugin) });
  }
  const allRoutes = collected.flatMap((item) => item.routes);
  validateCatalogConflicts(allRoutes, plugins);
  const aliases = await loadGroupAliases();
  await validateGroupAliasReferences(plugins);
  await validateNavigationIconReferences(plugins);
  const dynamic = allRoutes.filter((route) => route.descriptor.paramNames.length > 0);
  if (dynamic.length > 0) {
    if (!isDynamicRoutesEnabled()) {
      // 默认静态：未启用动态路由开关 → 任何动态 route 硬失败（与历史行为一致）。
      throw new Error(
        `Host capability gate 失败 (UNSUPPORTED_DYNAMIC_PLUGIN_ROUTE): 默认静态 Host 不支持动态 Plugin Route；如需启用请在 frontend/.env 设置 ADMIN_SURFACE_DYNAMIC_ROUTES=true\n${dynamic
          .map((route) => `- ${route.descriptor.routeId} (${route.descriptor.pattern})`)
          .join('\n')}`,
      );
    }
    // 已启用动态：静态导出 Host 仍要求动态 page 自带 generateStaticParams（构建期枚举）。
    const missing = dynamic.filter((route) => !route.hasGenerateStaticParams);
    if (missing.length > 0) {
      throw new Error(
        `Host capability gate 失败 (DYNAMIC_ROUTE_REQUIRES_GENERATE_STATIC_PARAMS): output:"export" 下动态 Plugin Route 必须自带 generateStaticParams\n${missing
          .map(
            (route) =>
              `- ${route.descriptor.routeId} (${route.descriptor.pattern}) @ plugins/${route.dirName}/routes/${route.dir || '.'}/page.tsx`,
          )
          .join('\n')}`,
      );
    }
  }
  return { plugins, allRoutes, aliases };
}

/* ------------------------------------------------------------------ */
/* Text builders（emission 与 freshness 共用同一文本生成，保证确定一致） */
/* ------------------------------------------------------------------ */

function buildCatalogText(plugins, allRoutes, aliases) {
  const lines = [
    "import type { AdminRouteCatalog } from '@community-go/admin-framework';",
    '',
    'export const generatedRouteCatalog: AdminRouteCatalog = {',
    '  plugins: [',
  ];
  for (const plugin of plugins) {
    lines.push(
      `    { pluginId: ${JSON.stringify(plugin.definition.pluginId)}, mount: ${JSON.stringify(plugin.definition.mount)} },`,
    );
  }
  lines.push('  ],');
  lines.push('  routes: [');
  for (const route of allRoutes) {
    lines.push('    {');
    for (const [key, value] of Object.entries(route.descriptor)) {
      if (value === undefined || value === null) continue;
      lines.push(`      ${key}: ${JSON.stringify(value)},`);
    }
    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('  aliases: [');
  for (const alias of aliases) {
    lines.push(
      `    { groupId: ${JSON.stringify(alias.groupId)}, labelKey: ${JSON.stringify(alias.labelKey)}${alias.order !== undefined ? `, order: ${JSON.stringify(alias.order)}` : ''} },`,
    );
  }
  lines.push('  ],');
  lines.push('  contributions: [');
  for (const plugin of plugins) {
    if (!plugin.navigationContribution) continue;
    lines.push('    {');
    lines.push(`      pluginId: ${JSON.stringify(plugin.definition.pluginId)},`);
    lines.push('      contribution: { parents: [');
    for (const parent of plugin.navigationContribution.parents ?? []) {
      lines.push('        {');
      lines.push(`          navigationId: ${JSON.stringify(parent.navigationId)},`);
      lines.push(`          labelKey: ${JSON.stringify(parent.labelKey)},`);
      lines.push(`          groupId: ${JSON.stringify(parent.groupId)},`);
      if (parent.order !== undefined)
        lines.push(`          order: ${JSON.stringify(parent.order)},`);
      if (parent.iconId !== undefined)
        lines.push(`          iconId: ${JSON.stringify(parent.iconId)},`);
      if (parent.routeId !== undefined)
        lines.push(`          routeId: ${JSON.stringify(parent.routeId)},`);
      if (parent.children?.length) {
        lines.push('          children: [');
        for (const child of parent.children) {
          lines.push('            {');
          lines.push(`              navigationId: ${JSON.stringify(child.navigationId)},`);
          lines.push(`              labelKey: ${JSON.stringify(child.labelKey)},`);
          lines.push(`              routeId: ${JSON.stringify(child.routeId)},`);
          if (child.order !== undefined)
            lines.push(`              order: ${JSON.stringify(child.order)},`);
          if (child.iconId !== undefined)
            lines.push(`              iconId: ${JSON.stringify(child.iconId)},`);
          lines.push('            },');
        }
        lines.push('          ],');
      }
      lines.push('        },');
    }
    lines.push('      ], },');
    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('};');
  return `${lines.join('\n')}\n`;
}

function buildCompositionText(plugins) {
  const i18nPlugins = plugins.filter((plugin) => plugin.hasI18n);
  const lines = [
    "import { createAdminRegistry } from '@community-go/admin-framework';",
    "import type { AdminRegistryModel } from '@community-go/admin-framework';",
    "import type { TranslationResources } from '@community-go/i18n';",
    "import { generatedRouteCatalog } from '../catalog/catalog';",
    "import { assertValidAdminSurfaceRegistry, mergeTranslationResources, type AdminSurfaceComposition } from '../../src/composition';",
    "import { surfaceShellI18nResources } from '../../src/i18n';",
    ...i18nPlugins.map(
      (plugin) =>
        `import { pluginI18nResources as pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)} } from '../../plugins/${plugin.dirName}/i18n';`,
    ),
    '',
    'export const generatedSurfaceRegistry: AdminRegistryModel =',
    '  createAdminRegistry(generatedRouteCatalog);',
    '',
    '// Surface composition/model boundary runtime invariant：navigation group 必须命中 Admin Surface taxonomy。',
    'assertValidAdminSurfaceRegistry(generatedSurfaceRegistry);',
    '',
    'export const generatedSurfaceI18nResources: TranslationResources = mergeTranslationResources(',
    '  surfaceShellI18nResources,',
    ...i18nPlugins.map(
      (plugin) => `  pluginI18nResources_${escapeIdentifier(plugin.definition.pluginId)},`,
    ),
    ');',
    '',
    'export const generatedAdminSurfaceComposition: AdminSurfaceComposition = {',
    '  registryModel: generatedSurfaceRegistry,',
    '  i18nResources: generatedSurfaceI18nResources,',
    '};',
    '',
  ];
  return lines.join('\n');
}

/**
 * (A) Surface 公共化 shim 的相对导入目标：shim 位于
 * generated/plugin-routes/<dirName>/<rel>/<kind>.ts，
 * 源模块在 plugins/<dirName>/routes/<rel>/<kind>.tsx。
 * 相对深度：shim 目录相对 surface 根为 generated/plugin-routes/<dirName>[/<rel>]，
 * 因此到 plugins 需回退 3 层（surface 根 → plugins）再加 dirName/routes/<rel>。
 */
function surfaceShimSourceSpecifier(pluginDirName, routeRelDir, kind) {
  const relDir = routeRelDir === '' ? '' : `${routeRelDir}/`;
  const depth = routeRelDir === '' ? 3 : 3 + routeRelDir.split('/').length;
  const up = '../'.repeat(depth);
  return `${up}plugins/${pluginDirName}/routes/${relDir}${kind}`;
}

/** (B) Host Next adapter 的本地文件路径（apps/admin-web/src/app/<mount 相对>）。 */
function hostAdapterPath(descriptor, kind) {
  return join(hostAppRoot, descriptor.pattern.replace(/^\//, ''), `${kind}.tsx`);
}

/** (A) shim 经 package exports 的公共 subpath（Host import 用）。 */
function surfaceShimSubpath(pluginDirName, routeRelDir, kind) {
  const relDir = routeRelDir === '' ? '' : `${routeRelDir}/`;
  return `${surfacePackageName}/plugin-routes/${pluginDirName}/${relDir}${kind}`;
}

/** (A) shim 文本：re-export 源模块 default（薄接线，无逻辑）；动态 page 附带转发 generateStaticParams。 */
function buildSurfaceShimText(
  pluginDirName,
  routeRelDir,
  kind,
  forwardGenerateStaticParams = false,
) {
  const lines = [
    `export { default } from ${JSON.stringify(surfaceShimSourceSpecifier(pluginDirName, routeRelDir, kind))};`,
  ];
  if (forwardGenerateStaticParams) {
    lines.push(
      `export { generateStaticParams } from ${JSON.stringify(surfaceShimSourceSpecifier(pluginDirName, routeRelDir, kind))};`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

/** (B) Host adapter 文本：re-export (A) shim default（薄接线）；动态 page 附带转发 generateStaticParams。 */
function buildHostAdapterText(
  pluginDirName,
  routeRelDir,
  kind,
  forwardGenerateStaticParams = false,
) {
  const lines = [
    `export { default } from ${JSON.stringify(surfaceShimSubpath(pluginDirName, routeRelDir, kind))};`,
  ];
  if (forwardGenerateStaticParams) {
    lines.push(
      `export { generateStaticParams } from ${JSON.stringify(surfaceShimSubpath(pluginDirName, routeRelDir, kind))};`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

async function ensureDir(path) {
  await mkdir(dirname(path), { recursive: true });
}

/** Prettier 格式化生成的文本（与 repo 根配置一致），保证 deterministic emission 与 format:check 同时通过。 */
async function formatCode(path, content) {
  const config = await prettier.resolveConfig(path);
  const parser = /\.(?:ts|tsx)$/.test(path) ? 'typescript' : 'babel';
  return prettier.format(content, { ...config, parser });
}

/** 渲染最终可写内容：固定 ownership header + prettier 格式化。 */
async function renderFinalContent(path, content) {
  return formatCode(path, `${GENERATED_HEADER}\n\n${content.replace(/^\n+/, '')}`);
}

/* ------------------------------------------------------------------ */
/* Expected artifact plan（渲染阶段：纯内存，无文件系统写入）            */
/* ------------------------------------------------------------------ */

/**
 * 构建完整 expected artifact plan（{ kind, path, content }）。
 *
 * catalog / composition / i18n index / surface shim / Host adapter 的全部文本
 * 构造与 prettier 格式化都在此完成——任何可能抛错的 render/serialization 都会在
 * mutation 之前暴露（validation-before-write / no partial output）。
 */
async function buildExpectedArtifacts(plugins, allRoutes, aliases) {
  const artifacts = [];
  const pushGenerated = async (local, text) => {
    const path = join(generatedRoot, local);
    artifacts.push({
      kind: 'generated-file',
      path,
      content: await renderFinalContent(path, text),
    });
  };
  await pushGenerated('catalog/catalog.ts', buildCatalogText(plugins, allRoutes, aliases));
  await pushGenerated('composition/composition.ts', buildCompositionText(plugins));
  await pushGenerated(
    'composition/i18n.ts',
    "export { generatedSurfaceI18nResources } from './composition';\n",
  );
  for (const route of allRoutes) {
    // 每个路由段：为段内每个 Next special file 生成 (A) surface 公共 shim + (B) Host adapter。
    for (const kind of route.specialFiles) {
      // 动态 page（启用动态路由且自带 generateStaticParams）需在两层转发 GS(SP)，
      // 否则 Next 在 adapter 层看不到构建期枚举。
      const forwardGenerateStaticParams =
        kind === 'page' ? route.hasGenerateStaticParams === true : false;
      await pushGenerated(
        `plugin-routes/${route.dirName}/${route.dir === '' ? '' : `${route.dir}/`}${kind}.ts`,
        buildSurfaceShimText(route.dirName, route.dir, kind, forwardGenerateStaticParams),
      );
      const adapterPath = hostAdapterPath(route.descriptor, kind);
      artifacts.push({
        kind: 'host-adapter',
        path: adapterPath,
        content: await renderFinalContent(
          adapterPath,
          buildHostAdapterText(route.dirName, route.dir, kind, forwardGenerateStaticParams),
        ),
      });
    }
  }
  return artifacts;
}

/* ------------------------------------------------------------------ */
/* Mutation / reconciliation                                          */
/* ------------------------------------------------------------------ */

/** 删除空目录（自下而上，不越过 hostAppRoot）。 */
async function pruneEmptyDirs(startDir) {
  let current = startDir;
  while (current !== hostAppRoot && current.startsWith(hostAppRoot + sep)) {
    let entries;
    try {
      entries = await readdir(current, { withFileTypes: true });
    } catch {
      break;
    }
    const meaningful = entries.filter(
      (entry) => !entry.name.startsWith('.') && entry.name !== 'node_modules',
    );
    if (meaningful.length > 0) break;
    const parent = dirname(current);
    await rm(current, { recursive: true, force: true });
    current = parent;
  }
}

/**
 * 执行 reconciliation（仅在全部 validation + preflight 通过后调用）：
 * rm/rewrite generatedRoot → create/update Host artifacts → delete stale owned
 * artifacts → prune 空目录。
 */
async function reconcileArtifacts(artifacts) {
  const expectedHostPaths = new Set(
    artifacts
      .filter((artifact) => artifact.kind === 'host-adapter')
      .map((artifact) => artifact.path),
  );

  // 1. generatedRoot：整树归本 Generator 所有（既有契约），rm + 重写。
  await rm(generatedRoot, { recursive: true, force: true });
  for (const artifact of artifacts) {
    if (artifact.kind !== 'generated-file') continue;
    await ensureDir(artifact.path);
    await writeFile(artifact.path, artifact.content);
  }

  // 2. Host adapter artifacts：create/update（ownership 已在 preflight 保证）。
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    await ensureDir(artifact.path);
    await writeFile(artifact.path, artifact.content);
  }

  // 3. delete stale generator-owned Host artifacts + prune 空目录。
  const removed = [];
  for (const file of await walk(hostAppRoot)) {
    if (!isHostAdapterCandidateFileName(basename(file))) continue;
    if (expectedHostPaths.has(file)) continue;
    const content = await readFile(file, 'utf8');
    if (!isGeneratorOwned(content)) continue;
    await rm(file, { force: true });
    removed.push(file);
  }
  for (const file of removed) {
    await pruneEmptyDirs(dirname(file));
  }
}

/* ------------------------------------------------------------------ */
/* Freshness check                                                     */
/* ------------------------------------------------------------------ */

async function checkFreshness() {
  const { plugins, allRoutes, aliases } = await collectSurface();
  const artifacts = await buildExpectedArtifacts(plugins, allRoutes, aliases);
  const drift = [];

  const expectedGeneratedPaths = new Set();
  for (const artifact of artifacts) {
    if (artifact.kind !== 'generated-file') continue;
    expectedGeneratedPaths.add(artifact.path);
    const local = `surfaces/admin/generated/${toPosix(relative(generatedRoot, artifact.path))}`;
    if (!existsSync(artifact.path)) {
      drift.push(`missing: ${local}`);
      continue;
    }
    const actual = await readFile(artifact.path, 'utf8');
    if (actual !== artifact.content) {
      drift.push(`drift: ${local}`);
    }
  }
  // stale generated file：generated 目录中存在但不再期望的文件
  for (const file of await walk(generatedRoot)) {
    if (!expectedGeneratedPaths.has(file)) {
      drift.push(
        `stale generated file: surfaces/admin/generated/${toPosix(relative(generatedRoot, file))}`,
      );
    }
  }

  const expectedHostPaths = new Set();
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    expectedHostPaths.add(artifact.path);
    const local = toPosix(relative(frontendRoot, artifact.path));
    if (!existsSync(artifact.path)) {
      drift.push(`missing: ${local}`);
      continue;
    }
    const actual = await readFile(artifact.path, 'utf8');
    if (!isGeneratorOwned(actual)) {
      drift.push(
        `host artifact ownership collision: ${local}（已存在且不属于 admin-plugin-codegen）`,
      );
    } else if (actual !== artifact.content) {
      drift.push(`drift: ${local}`);
    }
  }
  // stale generator-owned Host artifact：通用扫描（无具体插件特判）
  for (const file of await walk(hostAppRoot)) {
    if (!isHostAdapterCandidateFileName(basename(file))) continue;
    if (expectedHostPaths.has(file)) continue;
    const content = await readFile(file, 'utf8');
    if (isGeneratorOwned(content)) {
      drift.push(`stale generator-owned host artifact: ${toPosix(relative(frontendRoot, file))}`);
    }
  }

  return drift;
}

/* ------------------------------------------------------------------ */
/* CLI                                                                */
/* ------------------------------------------------------------------ */

async function main() {
  const check = process.argv.includes('--check');
  if (check) {
    const drift = await checkFreshness();
    if (drift.length > 0) {
      console.error(
        `Admin codegen freshness check failed:\n${drift.map((item) => `- ${item}`).join('\n')}`,
      );
      process.exitCode = 1;
      return;
    }
    console.log('Admin codegen is fresh.');
    return;
  }
  const { plugins, allRoutes, aliases } = await collectSurface();
  const artifacts = await buildExpectedArtifacts(plugins, allRoutes, aliases);

  // Physical ownership preflight：期望 Host artifact 已存在且不属于本 Generator
  // → deterministic fail。此时尚未发生任何文件系统 mutation。
  const collisions = [];
  for (const artifact of artifacts) {
    if (artifact.kind !== 'host-adapter') continue;
    if (!existsSync(artifact.path)) continue;
    const actual = await readFile(artifact.path, 'utf8');
    if (!isGeneratorOwned(actual)) {
      collisions.push(toPosix(relative(frontendRoot, artifact.path)));
    }
  }
  if (collisions.length > 0) {
    throw new Error(
      `Host artifact ownership collision（preflight 失败，未写入/删除任何文件）:\n${collisions
        .map((path) => `- ${path}`)
        .join('\n')}`,
    );
  }

  await reconcileArtifacts(artifacts);
  console.log(`Admin codegen generated: ${plugins.length} plugins, ${allRoutes.length} routes.`);
}

await main();
