package composition

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateAdminRegistry renders the WebUI registry from the same composition Catalog.
func GenerateAdminRegistry() (string, error) {
	catalog, err := applicationAdminCatalog()
	if err != nil {
		return "", err
	}
	entries := make([]struct{ id, source string }, 0)
	for _, binding := range catalog.Bindings {
		for _, entry := range binding.Entries {
			source := strings.TrimSuffix(filepath.ToSlash(entry.SourcePath), filepath.Ext(entry.SourcePath))
			entries = append(entries, struct{ id, source string }{entry.ID, "../../../" + source})
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].id < entries[j].id })
	var builder strings.Builder
	builder.WriteString("// Code generated by admin-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&builder, "export const adminRevision = %q;\n\n", catalog.Revision)
	builder.WriteString("export const adminEntryRegistry = {\n")
	for _, entry := range entries {
		fmt.Fprintf(&builder, "  %q: () => import(%q),\n", entry.id, entry.source)
	}
	builder.WriteString("} as const;\n")
	return builder.String(), nil
}
