package composition

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	webuicontract "github.com/rin721/go-scaffold-template/internal/webui"
)

// GenerateWebUIRegistry renders the WebUI registry from the same composition Catalog.
func GenerateWebUIRegistry() (string, error) {
	catalog, err := applicationWebUICatalog()
	if err != nil {
		return "", err
	}
	repositoryRoot, err := webUIRepositoryRoot()
	if err != nil {
		return "", err
	}
	entries := make([]struct{ id, source string }, 0)
	locales := make([]webuicontract.Locale, 0)
	for _, binding := range catalog.Bindings {
		if len(binding.Entries) > 0 && len(binding.Locales) == 0 {
			return "", fmt.Errorf("validate webui module %q: locale binding is required when entries are declared", binding.ModuleID)
		}
		for _, entry := range binding.Entries {
			if err := validateWebUISourceFile(repositoryRoot, entry.SourcePath); err != nil {
				return "", fmt.Errorf("validate webui entry %q: %w", entry.ID, err)
			}
			source := strings.TrimSuffix(filepath.ToSlash(entry.SourcePath), filepath.Ext(entry.SourcePath))
			entries = append(entries, struct{ id, source string }{entry.ID, "../../../" + source})
		}
		for _, locale := range binding.Locales {
			if err := validateWebUILocaleFile(repositoryRoot, locale); err != nil {
				return "", fmt.Errorf("validate webui locale %q/%q: %w", locale.Language, locale.Namespace, err)
			}
			locales = append(locales, locale)
		}
		if err := validateWebUILocaleCoverage(repositoryRoot, binding); err != nil {
			return "", err
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].id < entries[j].id })
	sort.Slice(locales, func(i, j int) bool {
		if locales[i].Language != locales[j].Language {
			return locales[i].Language < locales[j].Language
		}
		return locales[i].Namespace < locales[j].Namespace
	})
	var builder strings.Builder
	builder.WriteString("// Code generated by webui-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&builder, "export const webuiRevision = %q;\n\n", catalog.Revision)
	builder.WriteString("export const webuiEntryRegistry = {\n")
	for _, entry := range entries {
		fmt.Fprintf(&builder, "  %q: () => import(%q),\n", entry.id, entry.source)
	}
	builder.WriteString("} as const;\n\n")
	builder.WriteString("export type WebUILocaleMessages = Readonly<Record<string, string>>;\n\n")
	builder.WriteString("export const webuiLocaleRegistry = {\n")
	currentLanguage := ""
	for _, locale := range locales {
		if locale.Language != currentLanguage {
			if currentLanguage != "" {
				builder.WriteString("  },\n")
			}
			fmt.Fprintf(&builder, "  %q: {\n", locale.Language)
			currentLanguage = locale.Language
		}
		source := "../../../" + filepath.ToSlash(locale.SourcePath)
		fmt.Fprintf(&builder, "    %q: () => import(%q).then(({ default: messages }) => messages as WebUILocaleMessages),\n", locale.Namespace, source)
	}
	if currentLanguage != "" {
		builder.WriteString("  },\n")
	}
	builder.WriteString("} as const;\n")
	return builder.String(), nil
}

func webUIRepositoryRoot() (string, error) {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("resolve webui generator source path")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "..", "..")), nil
}

func validateWebUISourceFile(repositoryRoot string, sourcePath string) error {
	fileInfo, err := os.Stat(filepath.Join(repositoryRoot, filepath.FromSlash(sourcePath)))
	if err != nil {
		return fmt.Errorf("stat %s: %w", sourcePath, err)
	}
	if !fileInfo.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file", sourcePath)
	}
	return nil
}

func validateWebUILocaleFile(repositoryRoot string, locale webuicontract.Locale) error {
	if err := validateWebUISourceFile(repositoryRoot, locale.SourcePath); err != nil {
		return err
	}
	content, err := os.ReadFile(filepath.Join(repositoryRoot, filepath.FromSlash(locale.SourcePath)))
	if err != nil {
		return fmt.Errorf("read %s: %w", locale.SourcePath, err)
	}
	messages := map[string]string{}
	if err := json.Unmarshal(content, &messages); err != nil {
		return fmt.Errorf("decode %s as string message map: %w", locale.SourcePath, err)
	}
	if len(messages) == 0 {
		return fmt.Errorf("%s has no messages", locale.SourcePath)
	}
	for messageID := range messages {
		if strings.TrimSpace(messageID) == "" {
			return fmt.Errorf("%s contains an empty message id", locale.SourcePath)
		}
	}
	return nil
}

func validateWebUILocaleCoverage(repositoryRoot string, binding webuicontract.Binding) error {
	if len(binding.Routes) == 0 && len(binding.Navigation) == 0 {
		return nil
	}
	type localeResource struct {
		language  string
		namespace string
		messages  map[string]string
	}
	resources := make([]localeResource, 0, len(binding.Locales))
	for _, locale := range binding.Locales {
		path := filepath.Join(repositoryRoot, filepath.FromSlash(locale.SourcePath))
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read locale %q/%q for coverage: %w", locale.Language, locale.Namespace, err)
		}
		messages := map[string]string{}
		if err := json.Unmarshal(content, &messages); err != nil {
			return fmt.Errorf("decode locale %q/%q for coverage: %w", locale.Language, locale.Namespace, err)
		}
		resources = append(resources, localeResource{language: locale.Language, namespace: locale.Namespace, messages: messages})
	}
	messageIDs := make([]string, 0, len(binding.Routes)+len(binding.Navigation))
	for _, route := range binding.Routes {
		messageIDs = append(messageIDs, route.TitleMessageID)
	}
	for _, item := range binding.Navigation {
		messageIDs = append(messageIDs, item.TitleMessageID)
	}
	for _, messageID := range messageIDs {
		parts := strings.Split(messageID, ".")
		if len(parts) < 2 {
			return fmt.Errorf("webui module %q message id %q has no namespace", binding.ModuleID, messageID)
		}
		namespace := strings.Join(parts[:2], ".")
		foundNamespace := false
		for _, resource := range resources {
			if resource.namespace != namespace {
				continue
			}
			foundNamespace = true
			if _, ok := resource.messages[messageID]; !ok {
				return fmt.Errorf("webui module %q locale %q/%q misses message %q", binding.ModuleID, resource.language, resource.namespace, messageID)
			}
		}
		if !foundNamespace {
			return fmt.Errorf("webui module %q has no locale namespace %q for message %q", binding.ModuleID, namespace, messageID)
		}
	}
	return nil
}
