package composition

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rin721/go-scaffold-template/internal/projectlayout"
)

const specLayoutFixture = `{"schemaVersion":1,"roots":{"webui":"webui","modules":"internal/module","tools":".tools/bin","release":"dist"},"webui":{"moduleFacet":"binding/webui/web","source":"webui/src","platformStyles":"webui/src/styles.css","registryOutput":"webui/src/generated/webui-registry.ts","specOutput":"webui/src/generated/openapi-spec.ts"},"generatedArtifacts":{"openapi":"api/openapi.yaml","operationInventory":"internal/transport/http/api/operation_inventory.gen.go"}}`

const specContractFixture = `openapi: 3.0.3
info:
  title: go-scaffold-template HTTP API
  version: 1.0.0-rc.1
paths:
  /api/v1/iam/session:
    get:
      operationId: iam.session.read
      responses:
        "200":
          description: OK
`

func writeSpecFixtureRepository(t *testing.T) (string, projectlayout.Layout) {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".scaffold"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "webui", "src", "generated"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "api"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "webui", "src"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "internal", "module"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".scaffold", "layout.json"), []byte(specLayoutFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "webui", "src", "styles.css"), []byte(":root{}"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "api", "openapi.yaml"), []byte(specContractFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	layout, err := projectlayout.Load(root, "")
	if err != nil {
		t.Fatal(err)
	}
	return root, layout
}

func TestGenerateWebUIOpenAPISpecForLayoutRendersJSONSnapshot(t *testing.T) {
	root, layout := writeSpecFixtureRepository(t)
	content, err := GenerateWebUIOpenAPISpecForLayout(layout, root)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"// Code generated by webui-gen; DO NOT EDIT.",
		"export const webuiOpenAPISpecSourceRevision = ",
		"export const webuiOpenAPISpec = {",
		`"title": "go-scaffold-template HTTP API"`,
		`"operationId": "iam.session.read"`,
	} {
		if !strings.Contains(content, expected) {
			t.Fatalf("generated spec does not contain %s:\n%s", expected, content)
		}
	}
	// 源 revision 必须等于 api/openapi.yaml 的 sha256。
	sum := sha256.Sum256([]byte(specContractFixture))
	if !strings.Contains(content, `"`+hex.EncodeToString(sum[:])+`"`) {
		t.Fatalf("generated spec misses source revision %s:\n%s", hex.EncodeToString(sum[:]), content)
	}
	// JSON 段必须可解析且顶层为 object。
	start := strings.Index(content, "export const webuiOpenAPISpec = ")
	if start < 0 {
		t.Fatal("generated spec has no webuiOpenAPISpec export")
	}
	objectStart := strings.Index(content[start:], "{")
	if objectStart < 0 {
		t.Fatal("generated spec has no JSON object")
	}
	payload := content[start+objectStart:]
	payload = strings.TrimSuffix(payload, ";\n")
	var document map[string]any
	if err := json.Unmarshal([]byte(payload), &document); err != nil {
		t.Fatalf("generated JSON object does not parse: %v\n%s", err, payload)
	}
	if document["openapi"] != "3.0.3" {
		t.Fatalf("generated spec has unexpected openapi field: %#v", document["openapi"])
	}
}

func TestWriteWebUIOpenAPISpecAtWritesAndChecks(t *testing.T) {
	root, layout := writeSpecFixtureRepository(t)
	written, err := WriteWebUIOpenAPISpecAt(root, layout, false)
	if err != nil {
		t.Fatal(err)
	}
	outputPath := filepath.Join(root, "webui", "src", "generated", "openapi-spec.ts")
	actual, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(actual) != written {
		t.Fatal("written spec file differs from returned content")
	}
	if _, err := WriteWebUIOpenAPISpecAt(root, layout, true); err != nil {
		t.Fatalf("check on fresh file error = %v", err)
	}
	// 篡改后 --check 必须失败（严格比对，防止静默漂移）。
	if err := os.WriteFile(outputPath, []byte(strings.Replace(written, "3.0.3", "3.0.0", 1)), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := WriteWebUIOpenAPISpecAt(root, layout, true); err == nil {
		t.Fatal("check on stale file error = nil")
	}
}

func TestGenerateWebUIOpenAPISpecForLayoutFailsWithoutContract(t *testing.T) {
	root, layout := writeSpecFixtureRepository(t)
	if err := os.Remove(filepath.Join(root, "api", "openapi.yaml")); err != nil {
		t.Fatal(err)
	}
	if _, err := GenerateWebUIOpenAPISpecForLayout(layout, root); err == nil {
		t.Fatal("missing contract error = nil")
	}
}