package composition

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rin721/go-scaffold-template/internal/projectlayout"
	"go.yaml.in/yaml/v3"
)

// WriteWebUIOpenAPISpecFromCurrentDirectory 在布局清单确定的仓库根写入或校验
// WebUI 契约浏览器快照（075）：`api/openapi.yaml` 是唯一物理权威，快照是其 JSON
// 变换，与 registry 共用同一 `webui generate [--check]` 门禁，防止静默漂移。
func WriteWebUIOpenAPISpecFromCurrentDirectory(check bool) error {
	repositoryRoot, layout, err := projectlayout.FindRepositoryRootFromCurrentDirectory()
	if err != nil {
		return err
	}
	if _, err := WriteWebUIOpenAPISpecAt(repositoryRoot, layout, check); err != nil {
		return err
	}
	return nil
}

// WriteWebUIOpenAPISpecAt 在指定仓库根写入（check=false）或严格校验（check=true）
// 契约浏览器快照；返回生成内容，供测试与独立生成入口复用。
func WriteWebUIOpenAPISpecAt(repositoryRoot string, layout projectlayout.Layout, check bool) (string, error) {
	content, err := GenerateWebUIOpenAPISpecForLayout(layout, repositoryRoot)
	if err != nil {
		return "", err
	}
	outputPath, err := layout.RepositoryPath(repositoryRoot, layout.WebUI.SpecOutput)
	if err != nil {
		return "", err
	}
	if check {
		actual, readErr := os.ReadFile(outputPath)
		if readErr != nil {
			return "", readErr
		}
		if string(actual) != content {
			return "", fmt.Errorf("generated file %q is stale", filepath.ToSlash(layout.WebUI.SpecOutput))
		}
		return content, nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return "", err
	}
	return content, nil
}

// GenerateWebUIOpenAPISpecForLayout 把 layout 声明的 `api/openapi.yaml` 解析并
// 渲染为 TS 模块：JSON 对象（键稳定排序，输出确定性）+ 源文件 sha256 常量。
// 契约缺失或解析失败必须报错，不输出占位文件（--check 与生成共用同语义）。
func GenerateWebUIOpenAPISpecForLayout(layout projectlayout.Layout, repositoryRoot string) (string, error) {
	openAPIPath, err := layout.RepositoryPath(repositoryRoot, layout.GeneratedArtifacts.OpenAPI)
	if err != nil {
		return "", err
	}
	payload, err := os.ReadFile(openAPIPath)
	if err != nil {
		return "", fmt.Errorf("read OpenAPI contract %q: %w", layout.GeneratedArtifacts.OpenAPI, err)
	}
	var document map[string]any
	if err := yaml.Unmarshal(payload, &document); err != nil {
		return "", fmt.Errorf("parse OpenAPI contract %q: %w", layout.GeneratedArtifacts.OpenAPI, err)
	}
	spec, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return "", fmt.Errorf("encode OpenAPI contract for the WebUI snapshot: %w", err)
	}
	digest := sha256.Sum256(payload)
	var builder strings.Builder
	builder.WriteString("// Code generated by webui-gen; DO NOT EDIT.\n")
	fmt.Fprintf(&builder, "// Source: %s sha256:%s\n", layout.GeneratedArtifacts.OpenAPI, hex.EncodeToString(digest[:]))
	builder.WriteString("\n")
	fmt.Fprintf(&builder, "export const webuiOpenAPISpecSourceRevision = %q;\n", hex.EncodeToString(digest[:]))
	builder.WriteString("\n")
	builder.WriteString("export const webuiOpenAPISpec = ")
	builder.Write(spec)
	builder.WriteString(";\n")
	return builder.String(), nil
}